<?
// $Id$

require_once("../journals/global.php");

include_once("./top.inc");

$query="SELECT * FROM shorts ORDER BY article_id DESC LIMIT 1";

$res=mysql_query($query) or die (error_page($query));

$article_id=mysql_result($res,0,0);
$username=stripslashes(mysql_result($res,0,1));
$text=stripslashes(mysql_result($res,0,2));

echo <<<EOT
<TABLE BORDER=0 width=400 align=center>
<TR><TD>
<blockquote><P>
$text
</P>

<P><SMALL>- $username</SMALL></P>
</blockquote>



</TD></TR></TABLE>
EOT;

include_once("bottom.inc");
?>