<?
// -*- Mode: PHP; indent-tabs-mode: nil; -*-
// $Id$
require_once("../journals/global.inc");
$urlbase = URLBASE;
include("../journals/insert_stats.inc");
?>

<html>
<head>
<title>swinney.org: Thought-O-Matic</title>

<meta http-equiv="expires" content="0">
<meta name="keywords" content=" austin swinney ;">

<?
 if ($refreshrate or $refreshrate = "0") {
echo "<meta http-equiv=\"refresh\" content=\"$refreshrate; url=index.phtml?refreshrate=$refreshrate\">"; 
}
?>

<link rel="stylesheet" type="text/css" href="<? echo $urlbase; ?>/journals/main.css">

<script type="text/javascript" language="JavaScript" src="../journals/rollover.js"></script>

<script type="text/javascript" language="JavaScript">
//<!--
MM1 = new rollover("ithoughtit","<? echo $urlbase; ?>/journals/img/ithoughtit.gif", "<? echo $urlbase; ?>/journals/img/ithoughtit-over.gif", "ithoughtit");
//-->
</script>

</head>

<body bgcolor="#cccccc" link="#000099" vlink="#330066" alink="#ff0000"
marginwidth=0 marginheight=0 topmargin=0 leftmargin=0>

<center><img src="../journals/img/thoughtomatic.gif" alt="The Swinney.org Thought-O-Matic" width="219" height="40" border="0"></center>

<table width="100%" cellpadding="20" cellspacing="0" border="0">
<tr>
<td bgcolor="#666666" align="center">
<table cellpadding="2" cellspacing="1" border="0">
<?
// include i thought it
include("./submit_thought.phtml");
?>

<tr>
<td bgcolor="#666666">
<table cellpadding="0" cellspacing="0" border="0" width="450">

<? 
// include the thoughts
include("./insert_thought.phtml"); 
?>
</table>


</td>
</tr>


<?
// include i thought it
include("./submit_thought.phtml");
?>

</table></td>

</tr>
</table>


<?
include("../journals/templates/footer.inc");
?>
