<? 
#$Id$
include "../templates/top.inc";
include "admin_nav.inc";
?>

<TABLE border=1 cellspacing=0 cellpading=0>
<TR>
<TD>comment_id</TD>
<TD>edit</TD>
<TD>username</TD>
<TD>comment</TD>
</TR>
<?


// this is set to determine header() in process_edit_comments.phtml
$previous=0;
echo "<!-- previous: $previous -->\n";

$res = mysql_query("select comment_id,username,comment,article_id from comments where status=0 order by comment_id DESC limit 20");

while ( $d = mysql_fetch_object ($res) ) {

$comment_id = $d->comment_id;
$username = $d->username;
$comment = $d->comment;
$article_id = $d->article_id;

echo "<TR><TD valign='top'>\n";
echo "<a href='http://swinney.org/journals/article.phtml?id=$article_id.txt#$comment_id'>($article_id) $comment_id</a></TD>\n";
echo "<TD valign='top'><a href='edit_comments.phtml?comment_id=$comment_id&previous=$previous'>=>edit<=</a></TD>";
echo "<TD valign='top'>$username</TD><TD>".stripslashes($comment)."</TD></TR>";

}
?>
</TABLE>
</BODY>
</HTML>




















