<!--
  This file is just a quick header file for the admin area, where people upload/review content
-->

<HTML>
<HEAD>
<TITLE>swinney.org</TITLE>
<META NAME="keywords" CONTENT=" Austin Swinney ;">
<STYLE TYPE="text/css">
<!--
p {  font-family: Arial, Helvetica, sans-serif; font-size: 10pt} 
/* so I don't have to fuck with font tags */
pre { color: navy } 
/* predefined colr name */
-->
</STYLE>
</HEAD>
<BODY BGCOLOR="#DED3D3" LINK="red">
<CENTER>
<TT><a href='../../index.phtml'>Swinney.org</a> Admin Area</TT></h3>
<P>
<a href='index.phtml'>firebird</a> | 
<a href='listcontent.phtml'>articles</a> | 
<a href='admin_comments.phtml'>comments</a>
</P>
</CENTER>
















