<?
// $Id$

  require_once("../global.inc");
  $title="The Engine Revs Mighty";
  include(INCDIR ."/top.inc");
  include(INCDIR ."/swinney.req");
?>

<center>
<p class="subheader">
<b>firebird</b> | 
<a href='listcontent.phtml'>articles</a> | 
<a href='admin_comments.phtml'>comments</a> | 
<a href='users.phtml'>users</a>
</p>
</center>

<pre>


</pre>
<center><img src='../img/car8.gif'></center>
<? include "../templates/footer.inc"; ?>


