<?
// $Id$

  require_once("../global.inc");
  $title="The Engine Revs Mighty";
  include("../templates/top.inc");
  include("../templates/swinney.req");
?>

<center>
<p class="subheader">
<b>firebird</b> | 
<a href='listcontent.phtml'>entries</a> | 
<a href='admin_comments.phtml'>comments</a> | 
<a href='users.phtml'>users</a>
</p>
</center>

<pre>


</pre>
<center><img src='http://swinney.org/journals/img/car8.gif'></center>
<? include "../templates/footer.inc"; ?>


