<?



$result_set = mysql( "textocal", "SELECT * FROM pending_articles;" );

$url = "../pending/";

// multiple rows 
while ( $individual_row = mysql_fetch_object( $result_set ) ) {

// one row
//$individual_row = mysql_fetch_object( $result_set ); 

   echo "<table width=200 border=1 cellspacing=0 cellpadding=3><tr><td>";
   echo "<a href=\"$url$individual_row->article_id.txt\"><B>$individual_row->title</a>:</B> ";
   echo "$individual_row->blurb</td></tr></table>\n";
}



?>
