<?
#$Id$
# include the templates/top.inc
include "../templates/top.inc";

?>

<CENTER>
<TT><a href='../../index.phtml'>Swinney.org</a> Admin Area</TT></h3>
<P>
<a href='index.phtml'>firebird</a> | 
<a href='listcontent.phtml'>articles</a> | 
<a href='admin_comments.phtml'>comments</a>
</P>
</CENTER>

<?

// update the articles

  if ( $type == "resubmit" ) {

    $res = mysql_query ("UPDATE articles_text SET text='$update' WHERE article_id=$article_id");

    if ( $subby == "Save and Exit" ) unset($article_id);

    // Update the status of the article
    //  if status is greater than or equal to 1 and greater than 
    //  or equal to 4 than update it in the database
    if ( $status >= 1 && $status <= 4 ) {

      $res = mysql_query("UPDATE articles_info 
		SET web='$web', status='$status', title='$title', blurb='$blurb' 
		WHERE article_id='$article_id'");

      if ( $res == false ) {
        error("Could not update pending_articles");
        exit;
      }
    }
  }


//
// Showing the article
//

/*

+------------+--------------+------+-----+---------+----------------+
| Field      | Type         | Null | Key | Default | Extra          |
+------------+--------------+------+-----+---------+----------------+
| article_id | int(11)      |      | PRI | 0       | auto_increment |
| username   | varchar(20)  | YES  |     | NULL    |                |
| web        | varchar(255) | YES  |     | NULL    |                |
| date       | date         | YES  |     | NULL    |                |
| time       | int(11)      | YES  |     | NULL    |                |
| status     | tinyint(4)   | YES  |     | NULL    |                |
| keywords   | varchar(100) | YES  |     | NULL    |                |
| title      | varchar(255) | YES  |     | NULL    |                |
| blurb      | varchar(255) | YES  |     | NULL    |                |
| category   | bigint(20)   | YES  |     | NULL    |                |
| image      | tinyint(4)   | YES  |     | NULL    |                |
+------------+--------------+------+-----+---------+----------------+ 
*/



if ( isset($article_id) ) {

// select the article list

	$res = mysql_query("SELECT keywords, title, blurb, status, image, web 
		FROM articles_info 
		WHERE article_id='$article_id'");
	$d=mysql_fetch_object($res);
    $keywords = $d->keywords;
    $title = $d->title;
    $blurb = $d->blurb;
    $status = $d->status;
    $images = $d->images;
    $web = $d->web;
    $keyarray = explode(',', $keywords);


// This is where the editing begins
    echo "<form action='listcontent.phtml' method='post'>";
    echo "<ul>";
    $count = 0;
    for ( $i = 0 ; ; $i++ ) {
      if ( $keyarray[$i] == "" ) break;
      echo "<li>".$keyarray[$i];
    }
    echo "</ul>";



//
// show images if they exist
//



// path to working directory
   $imagepath = "http://swinney.org/journals/images/";

    for ( $i = 1; $i <= $images ; $i++ ) {
      $noext = $article_id."_".$i;

      if (file_exists ( "/sky/www/swinney.org/html/journals/images/".$noext.".jpg")) {
// find out if the basename exists as a jpeg
        $imgfile = "$imagepath$noext.jpg";

        echo "<h3>$imgfile<br>";
        echo "<tt>&lt;img src='$imgfile' height='150' align='left'&gt;</tt></h3><br>";
        echo "<img src='$imgfile' height='150'><br>";
      }
      elseif ( file_exists ("/sky/www/swinney.org/html/journals/images/".$noext.".gif")) {
// no, so we'll see if it exists as a gif
        $imgfile = "$imagepath$noext.gif";

        echo "<h3>$imgfile<br>";
        echo "<tt>&lt;img src='$imgfile' height='150' align='left'&gt;</tt></h3><br>";
        echo "<img src='$imgfile' height='150'><br>";
      }
      elseif ( file_exists ("/sky/www/swinney.org/html/journals/images/".$noext.".png")) {
// no, so we'll see if it exists as a png
        $imgfile = "$imagepath$noext.png";

        echo "<h3>$imgfile<br>";
        echo "<tt>&lt;img src='$imgfile' height='150' align='left'&gt;</tt></h3><br>";
        echo "<img src='$imgfile' height='150'><br>";
      }
      else {
// holy shit!  it's neither!
        echo "shit! $i<br>";
        echo "$imgfile<BR>";   
      }
    }         


//
// show article stuff
//


if ($web != "") 

{

	if (substr($web,0,7) !='http://' && substr($web,0,7) !='mailto:') 

	{


		if (strstr($web,'@')) 

		{ 
			$web = "mailto:$web"; 

		} 

			else 

		{ 

			$web = "http://$web"; 

		}

	}

}

    echo "<h2>web: <a href=\"$web\">$web</a></h2>";
    echo "<textarea name=web cols=60 rows=2>$web</textarea>";
    echo "<h2>Title: ".stripslashes($title)."</h2>";
    echo "<textarea name=title cols=60 rows=2>".stripslashes($title)."</textarea>";
    echo "<h3>Blurb: ".stripslashes($blurb)."</h3>";
    echo "<textarea name=blurb cols=60 rows=3>".stripslashes($blurb)."</textarea>";


// Look up the article

$res = mysql_query("SELECT text FROM articles_text WHERE article_id='$article_id'");

$row = mysql_fetch_row($res);
$text = $row[0];

if ( isset($article_id) ) {

    echo "<input type='hidden' name='type' value='resubmit'>\n";
    echo "<input type='hidden' name='article_id' value='$article_id'>\n";
    echo "<table border=0 width=400><tr><td>$text</td></tr></table>\n<br>\n<br>\n";
    echo "<textarea name=update cols=80 rows=20 wrap=virtual>$text</textarea>\n<br>\n";

} 


//gonna f*ck with my status now?!


    echo "<b>Status : </b> <select name='status'>";
    if ( $status == 1 ) {
      echo "<option value='1' selected>Pending";
    } else if ( $status == 2 ) {
      echo "<option value='2' selected>Active";
    } else if ( $status == 3 ) {
      echo "<option value='3' selected>Archived";
    } else if ( $status == 4 ) {
      echo "<option value='4' selected>Trash";
    }
    echo "<option>---\n";
    echo "<option value='1'>Pending\n";
    echo "<option value='2'>Active\n";
    echo "<option value='3'>Archived\n";
    echo "<option value='4'>Trash\n";

    echo "</select>\n";

    echo "<p>";
    echo "<input name='subby' type='submit' value='Save and Reload'>\n";
    echo "<input name='subby' type='submit' value='Save and Exit'>\n";
    echo "<br><br>\n";
    echo "</form>\n";

    exit;
  }

// article list

  echo "<p>";
  $res = mysql_query("SELECT * FROM articles_info WHERE status<>4 ORDER BY article_id DESC LIMIT 20");
  
  echo "<table cellpadding=4 cellspacing=0 border=1 align=center>";
  echo "<tr>";
  echo "<td align=center><b>ID</b></td>\n";
  echo "<td align=center><b>Username</b></td>\n";
  echo "<td align=center><b>Date</b></td>\n";
  echo "<td align=center><b>Status</b></td>\n";
  echo "<td align=center><b>Title</b></td>\n";
  echo "<td align=center><b>Blurb</b></td>\n";
  echo "<td align=center><b>comments</b></td>\n";

  echo "</tr>";
  while ( $d = mysql_fetch_object($res) ) {
    echo "<tr>";
    echo "<td align=center><b><a href='../article.phtml?id=$d->article_id.txt'>$d->article_id</a></b></td>\n";
    echo "<td align=center><b>$d->username</b></td>\n";
    echo "<td align=center>$d->date</td>\n";


    switch ( $d->status ) {
      case 0 : $str = "";  break;
      case 1 : $str = "<font color='red'>Pending</font>";  break;
      case 2 : $str = "<font color='green'>Accepted</font>";  break;
      case 3 : $str = "<font color='gray'>Archived</font>";  break;
      case 4 : $str = "<font color='gray'>Trash</font>";  break;
    }

    echo "<td align=center>$str</td>\n";
    echo "<td align=center><a href='listcontent.phtml?article_id=$d->article_id'>$d->title</a></td>\n";
    echo "<td align=center>$d->blurb</td>\n";



//  grab out the number of comments associated with this article
//  i tried to do this using count(*) but it was returning a numbering from 4 on (5,6,7...)
//  so i changed to mysql_num_rows() on the results from selecting all the comment_id's associated
//  with the article_id's.  :)    

    $comments = mysql_query("SELECT comment_id 
		FROM comments 
		WHERE article_id=$d->article_id");
    $num_comments=mysql_num_rows($comments);
    echo "<td align=center><a href='admin_comments_article.phtml?article_id=$d->article_id'>$num_comments</a></td>\n";
    echo "</tr>\n";

 }
    echo "</table>\n";

?>









