  // Display the selection critieria
  $res = mysql("$DB", "SELECT * FROM categories");
  $subject_value = 0;
  echo "<form action='listcontent.phtml' method='post'>";
  while ( $d = mysql_fetch_object($res) ) {
    $str = "cat".$d->category_id;
    if ( $$str == "on" ) {
      echo "$d->name : <input type='checkbox' name='cat$d->category_id' checked><br>";
      $val = pow(2, $d->category_id-1);
      $subject_value += $val;
    } else {
      echo "<TABLE border='no' border=0><TR>\n";
      echo "<TD>$d->name : <input type='checkbox' name='cat$d->category_id'></TD>\n";
      echo "</TR></TABLE>\n";
    }
  }
  echo "<input type='submit' value='Select Articles'>";
  echo "</form>";
  echo "<hr>";
