
<!-- BEGIN SUBMIT FORM FIELDS FOR ARTICLE INFO FILE: submit_article_info.inc --> 

<TR>

<TD>

<P>Title</P>

</TD>

<TD ALIGN="right">

<INPUT TYPE=text NAME=Title SIZE=40>

</TD>

</TR>

<TR>

<TD ALIGN="left">

<P>Keywords</P>

</TD>

<TD ALIGN="right">

<INPUT TYPE=text NAME=Keywords SIZE=40>

</TD>

</TR>

<TR>

<TD COLSPAN=2>

<TEXTAREA TYPE=text  NAME=Entry COLS=50 ROWS=20></TEXTAREA>

</TD>

</TR>

</TABLE>

<!-- END: submit_article_info.inc -->









