

<!-- BEGIN PHP Dynamic Processing File: submit_action.phtml -->

<?php

echo "<P>$FileName</P>";
echo "<P>$Name</P>";
echo "<P>$Email</P>";
echo "<P>$Title</P>";
echo "<P>$Keywords</P>";
echo "<P>$Entry</P>";


mysql_connect ("sql.dreamhost.com", "aswinney", "XXXXXXXX");

mysql_select_db (textocal);

mysql_query (

	
	"INSERT INTO swinicle (
		FileName,
		Name,
		Email,
		Title,
		Keywords)
	VALUES (
		'$FileName',
		'$Name',
		'$Email',
		'$Title',
		'$Keywords')
	");
mysql_query (

	"INSERT INTO articles_tbl (
		FileName,
		Entry)

	VALUES (
		'$FileName',
		'$Entry')
	");




?>

<!-- END PHP Dynamic Processing File: submit_action.phtml -->









