




<!-- BEGIN INCLUDED CODE CHUNK FOR PERSONAL INFO FIELDS: submit_personal_info.inc -->

<form action="submit_process.phtml" method=get>

<TABLE WIDTH=400 BORDER=0 CELLSPACING=0 CELLPADDING=0>

<TR>

<TD ALIGN="left" WIDTH=200>

<P>Your Name</P>

</TD>

<TD ALIGN="right">

<INPUT TYPE=text NAME=Name SIZE=40>

</TD>

</TR>

<TR>

<TD>Neopets Name</TD>

<TD ALIGN="right">

<INPUT TYPE=TEXT NAME=NeoName SIZE=40>

</TD>

</TR>

<TR>

<TD>Email</TD>

<TD ALIGN="right">

<INPUT TYPE=text NAME=Email SIZE=40>

</TD>

</TR>

<!-- END: submit_personal_info.inc -->


<!-- BEGIN SUBMIT FORM FIELDS FOR ARTICLE INFO FILE: submit_article_info.inc --> 

<TR>

<TD>

<P>Title</P>

</TD>

<TD ALIGN="right">

<INPUT TYPE=text NAME=Title SIZE=40>

</TD>

</TR>

<TR>

<TD ALIGN="left">

<P>Keywords</P>

</TD>

<TD ALIGN="right">

<INPUT TYPE=text NAME=Keywords SIZE=40>

</TD>

</TR>

<TR>

<TD COLSPAN=2>

<TEXTAREA TYPE=text  NAME=Entry COLS=50 ROWS=20></TEXTAREA>

</TD>

</TR>

</TABLE>

<!-- END: submit_article_info.inc -->



<!-- BEGIN SUBMIT ARTICLE CATEGORIES INCLUDE: submit_article_categories.inc -->

<P>In your oppinion, where should your article be listed?  
Please do not select more than 3 or 4 sub categories.  
This isn't bingo!</P>

<BR><INPUT TYPE=CHECKBOX NAME= # VALUE=ON> BODY & SOUL
	<BLOCKQUOTE>
	<BR><INPUT TYPE=CHECKBOX NAME= # VALUE=ON>Health Notes
	<BR><INPUT TYPE=CHECKBOX NAME= # VALUE=ON>Happiness Tips
	<BR><INPUT TYPE=CHECKBOX NAME= # VALUE=ON>Features
	<BR><INPUT TYPE=CHECKBOX NAME= # VALUE=ON>Articles
	</BLOCKQUOTE>
<BR><INPUT TYPE=CHECKBOX NAME= # VALUE=ON> ARTS & ENTERTAINMENT
	<BLOCKQUOTE>
	<BR><INPUT TYPE=CHECKBOX NAME= # VALUE=ON>Music
	<BR><INPUT TYPE=CHECKBOX NAME= # VALUE=ON>Movies
	<BR><INPUT TYPE=CHECKBOX NAME= # VALUE=ON>TV
	<BR><INPUT TYPE=CHECKBOX NAME= # VALUE=ON>Games
	<BR><INPUT TYPE=CHECKBOX NAME= # VALUE=ON>Books
	</BLOCKQUOTE>
<BR><INPUT TYPE=CHECKBOX NAME= # VALUE=ON> STYLE & FASHION
	<BLOCKQUOTE>
	<BR><INPUT TYPE=CHECKBOX NAME= # VALUE=ON>News
	<BR><INPUT TYPE=CHECKBOX NAME= # VALUE=ON>Designers
	<BR><INPUT TYPE=CHECKBOX NAME= # VALUE=ON>Reviews
	<BR><INPUT TYPE=CHECKBOX NAME= # VALUE=ON>Articles
	</BLOCKQUOTE>
<BR><INPUT TYPE=CHECKBOX NAME= # VALUE=ON> SOCIETY
	<BLOCKQUOTE>
	<BR><INPUT TYPE=CHECKBOX NAME= # VALUE=ON>News
	<BR><INPUT TYPE=CHECKBOX NAME= # VALUE=ON>Politics
	<BR><INPUT TYPE=CHECKBOX NAME= # VALUE=ON>View Points
	<BR><INPUT TYPE=CHECKBOX NAME= # VALUE=ON>Advice (From Moms and Dads)
	</BLOCKQUOTE>
<BR><INPUT TYPE=CHECKBOX NAME= # VALUE=ON> SPORTS
	<BLOCKQUOTE>
	<BR><INPUT TYPE=CHECKBOX NAME= # VALUE=ON>News
	<BR><INPUT TYPE=CHECKBOX NAME= # VALUE=ON>Spotlight
	</BLOCKQUOTE>

<!-- END: submit_article_categories.inc -->





























