<!--
$Id$
#####################################
# top.inc - super hyper dynamic
# include file for all of swinney.org
# change this and change the world.
# Austin Swinney, of course.
# Thu Jul  5, 2001  7:54 AM
#####################################
-->

<?
// connect to the database
include "/sky/users/swinney/htdocs/dev/swinney.org/journals/global.inc";
conn();
?>

<HTML>
<HEAD>
<TITLE>swinney.org</TITLE>
<META NAME="keywords" CONTENT=" Austin Swinney ;">
<META HTTP-EQUIV="Expires" CONTENT="0">
<STYLE TYPE="text/css">
<!--
/* so I don't have to fuck with font tags */
p {  font-family: Times New Roman, Times, serif; font-size: 10pt} 
/* predefined colr name */
pre { color: navy } 

real {
position: absolute;
top: 0em;
right: 0em;
}

-->
</STYLE>
</HEAD>
<BODY bgcolor="CCCCCC" marginwidth=0 marginheight=0 leftmargin=0 topmargin=0>

<!-- END PHP Dynamically Required File: top.inc -->








