<!-- END PHP Dynamically Required File: top.inc -->

<?
// connect to the database
include "global.inc";
?>

<HTML>
<HEAD>
<TITLE>swinney.org</TITLE>
<META NAME="keywords" CONTENT=" Austin Swinney ;">
<META HTTP-EQUIV="Expires" CONTENT="0">
<STYLE TYPE="text/css">
<!--
p {  font-family: Arial, Helvetica, sans-serif; font-size: 10pt} 
/* so I don't have to fuck with font tags */
pre { color: navy } 
/* predefined colr name */
-->
</STYLE>
</HEAD>
<BODY>



<!-- END PHP Dynamically Required File: top.inc -->



