# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bde57177cd2aa32c42c0be02e3f4a9ddee80895dc0d42ff1868f911cdc4f27a8f353ea2015381865d0c5a4199956c57461f6880abe94e36252e5fa553ba4ec11

test:
  secret_key_base: 66fe3b38ff83b1bb6306582216a2edb0dc434c3a94b079dc57e92be4ced602b98af5df38fd4f0ca132658a61af0c4be5198fd949ba6f217e950667e970ea3cb8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
