
<!-- BEGIN PHP Dynamically Required File: endleft.inc -->

<td width="15">
<img src="<? echo URLBASE ?>/journals/img/no.gif" alt="" width="15" height="1" border="0"></td>

<td width="1" bgcolor="#999999">
<img src="<? echo URLBASE ?>/journals/img/no.gif" alt="" width="1" height="1" border="0"></td>

<td width="1">
<img src="<? echo URLBASE ?>/journals/img/no.gif" alt="" width="1" height="1" border="0"></td>

<td width="1" bgcolor="#999999">
<img src="<? echo URLBASE ?>/journals/img/no.gif" alt="" width="1" height="1" border="0"></td>

<td width="15">
<img src="<? echo URLBASE ?>/journals/img/no.gif" alt="" width="15" height="1" border="0"></td>

<td width="375" valign="top" align="left">

<!-- END PHP Dynamically Required File: endleft.inc -->
