
<map name="slymap">
<area shape="rect" coords="208,2,216,18" href="<? echo URLBASE; ?>/journals/admin/index.phtml">
<area shape="rect" coords="128,2,137,18" href="http://swinney.org/cgi/cvsweb.cgi/swinney.org/">
<area shape="default" href="<? echo URLBASE; ?>">
</map>

<table width="100%">
<tr>
<td>
<img src="<? echo URLBASE; ?>/journals/img/no.gif" alt="" width="58" height="30" border="0">
</td>
</tr>

<tr>
<td align="center">
<img src="<? echo URLBASE; ?>/journals/img/swinneylovesyou.gif" alt="Copyright 2001, Swinney Loves You" width="517" height="20" border="0" usemap="#slymap"></td>
</tr>

<tr>
<td>
<img src="<? echo URLBASE; ?>/journals/img/no.gif" alt="" width="58" height="30" border="0">
</td>
</tr>
</table>
</body>
</html>