<?
#$Id$

###################################
# rollcall.inc - who is out there?
# this is the most major shit script
# in all of swinney.org.  UNTIL TODAY
# i just figured out how to generate the
# entire thing in one select statement.
# worship me.  suck my dick.  it does not matter
# i do this all for the bitches.  word up 
# in two thousand.  -OMS 
# Thu Jul 12, 2001 10:13 AM
#
# mmmm...the bitches. - J. 020010921

?>

<!-- BEGIN PHP Dynamically Required File: norollcall.inc -->


<table cellpadding="0" cellspacing="0" border="0" width="100%">
<tr>
<td align="center">

<img src="<? echo URLBASE ?>/journals/img/no.gif" alt="" width="1" height="10" border="0"><br>

<table cellpadding="0" cellspacing="0" border="0">
<tr>
<td>


<!-- END PHP Dynamically Required File: norollcall.inc -->











