







<!-- BEGIN PHP Dynamically Required File: rollcall.inc -->


<TABLE WIDTH="100%" BORDER="1" CELLSPACING="0" CELLPADDING="2" BORDERCOLOR="#333333">

<TR BGCOLOR="#999999">
<TD>
<DIV ALIGN="center"><FONT FACE="Verdana, Arial, Helvetica, sans-serif" SIZE="2"><STRONG><FONT COLOR="#333333">Next?</FONT></STRONG></FONT></DIV>
</TD>
</TR>
<TR BGCOLOR="#DED3D3" ALIGN="left" VALIGN="top">
<TD>
<DIV ALIGN="left">
<P><FONT FACE="Verdana, Arial, Helvetica, sans-serif" SIZE="2">

<!-- WHAT IS GOING ON IN THE WORLD...  WHO?  -->

<script language="JavaScript">
     
function jumplink(url) {
     
	self.location = url;
     
}
</script> 


<?
include "../global.inc";

$res = mysql ("$DB", "SELECT DISTINCT username FROM pending_articles WHERE status='2' ORDER BY username");


echo "<form name='linkform'>";

echo "<select name='link' onChange='jumplink(this.options[this.selectedIndex].value)'>";

echo "<option>- - -</option>";

while ($row = mysql_fetch_object ($res)) {

  echo "<option value=\"../userpages.phtml?username=$row->username\">$row->username</option>\n";

}

echo "</SELECT>\n";
echo "</FORM>\n";


?>

</FONT>
</P>
</TD>
</TR>
</table>

<!-- include that final line break or the entire thing will be fucked. -->

<BR>

<!-- END PHP Dynamically Required File: rollcall.inc -->











