<?

#####################################
# $Id$
# top.inc - super hyper dynamic
# include file for all of swinney.org
# change this and change the world.
# Austin Swinney, of course.
# Thu Jul  5, 2001  7:54 AM
#####################################

$css_url = CSS_URL;
echo <<<EOT
<HTML>
<HEAD>
<TITLE>swinney.org</TITLE>
<META NAME="keywords" CONTENT=" Austin Swinney ;">
<META HTTP-EQUIV="Expires" CONTENT="0">
<LINK REL="stylesheet" type="text/css" href="$css_url">
</HEAD>
<BODY>

<!-- END PHP Dynamically Required File: top.inc -->

EOT;
?>
