<!--
$Id$
#####################################
# top.inc - super hyper dynamic
# include file for all of swinney.org
# change this and change the world.
# Austin Swinney, of course.
# Thu Jul  5, 2001  7:54 AM
#####################################
-->

<?
// connect to the database
include "journals/global.inc";
conn();
?>

<HTML>
<HEAD>
<TITLE>swinney.org</TITLE>
<META NAME="keywords" CONTENT=" Austin Swinney ;">
<META HTTP-EQUIV="Expires" CONTENT="0">
<STYLE TYPE="text/css">
<!--

body { bgcolor:"CCCCCC"; marginwidth:0; marginheight:0; leftmargin:0; topmargin:0 }
p {  font-family: Times New Roman, Times, serif; font-size: 10pt} 
pre { color: navy } 
real { position: absolute; top: 0em; right: 0em; }

-->

</STYLE>
</HEAD>
<BODY>

<!-- END PHP Dynamically Required File: top.inc -->








