<?
require_once("../global.php");
$title="Edit last submitted article";
if (isset($_SESSION['authenticated_username'])) {
  $query="SELECT articles_info.web,
                 articles_info.title,
                 articles_info.blurb,
                 articles_info.keywords,
                 articles_info.category,
                 articles_text.text,
                 articles_info.article_id,
                 articles_info.status
            FROM articles_info, 
                 articles_text 
           WHERE username='$_SESSION['authenticated_username']' 
             AND articles_info.article_id=articles_text.article_id 
        ORDER BY articles_info.article_id DESC
           LIMIT 1";
  $res=mysql_query($query) or die(error_page($query));
  if ($res) {
    $web          =stripslashes(mysql_result($res,0,0));
    $temp_title   =stripslashes(mysql_result($res,0,1));
    $blurb        =stripslashes(mysql_result($res,0,2));
    $keywords     =stripslashes(mysql_result($res,0,3));
    $category     =             mysql_result($res,0,4);
    $text         =stripslashes(mysql_result($res,0,5));
    $temp_aid     =             mysql_result($res,0,6);
    $status       =             pretty_status(mysql_result($res,0,7));
    // register this temp_aid to keep it from messing up the usual
    // var article_id.
    session_register("temp_aid");
  }   
} else {
  error_page("username unset");
}

include_once(INCDIR ."/top.inc");
include_once(INCDIR ."/swinney.req");
include_once(INCDIR ."/norollcall.inc");
include_once("../submit_article.inc");
include_once(INCDIR ."/bottom.req");
include_once(INCDIR ."/footer.inc");

?>
