<?
// -*- Mode: PHP; indent-tabs-mode: nil; -*-
// $Id$
require_once("./global.inc");

// check submitted and confirmation passwords
if ($old_password && $new_password1 && $new_password2) {
  // pull existing user info
$query = <<<EOT
SELECT user_id, password
  FROM user
 WHERE username='$authenticated_username'
EOT;

 $res = mysql_query($query) or
   die(error_page(mysql_error()));
 $user = mysql_fetch_object($res) or
   die(error_page(mysql_error()));

 // compare old password to database password
 if (crypt($old_password, $user->password) == $user->password) {

    if ($new_password1 == $new_password2) {

      // update the password in the database
      $encrypted_password = crypt($new_password1);

      $query = <<<EOT
UPDATE user
   SET password='$encrypted_password'
 WHERE user_id=$user->user_id;
EOT;

      if (mysql_query($query)) {
        $success_msg = "Your password has been changed.";
      } else {
        $error_msg = "Error saving your new password: " . mysql_error();
      }
    } else {
      $error_msg = "The new passwords don't match. Try again:";
    }
  } else {
    $error_msg = "Current password incorrect. Try again:";
  }
} else {
  $error_msg = "You must fill in all fields. Try again:";
}

if ($error_msg) {
  $title = "Change Your Password";
  $into_template = "./submit_change_password.inc";
} else {
  $title = "Settings";
  $into_template = "./index.inc";
}

include(INCDIR ."/template.inc");
?>

