<?

require_once("./global.inc");

// check submitted and confirmation passwords
if ($old_password && $new_password1 && $new_password2) {
  // pull existing user info
$query = <<<EOT
SELECT user_id, password
  FROM user
 WHERE username='$authenticated_username'
EOT;

 $res = mysql_query($query) or
   die(error_page(mysql_error()));
 $user = mysql_fetch_object($res) or
   die(error_page(mysql_error()));

 // compare old password to database password
 if (crypt($old_password, $user->password) == $user->password) {

    if ($new_password1 == $new_password2) {

      // update the password in the database
      $encrypted_password = crypt($new_password1);

      $query = <<<EOT
UPDATE user
   SET password='$encrypted_password'
 WHERE user_id=$user->user_id;
EOT;

      mysql_query($query) or
        die(error_page(mysql_error()));

      $success_msg = "Your password has been changed.";
    } else {
      $error_msg = "The new passwords do not match. Try again.";
    }
  } else {
    $error_msg = "The old password is invalid. Try again.";
  }
} else {
  $error_msg = "You must fill in all fields. Try again.";
}

include("./submit_change_password.phtml");

?>

