<?
// -*- Mode: PHP; indent-tabs-mode: nil; -*-
// $Id$

require_once("./global.inc");

if ($remove) {
  // maintain a list of usernames that have been successfully removed
  foreach ($username as $u) {
    if (!$del) {
      $del = "$u";
    } else {
      $del .= ",$u";
  }

      $query = <<<EOT
DELETE FROM user_bozo
      WHERE user_id=$authenticated_user_id
        AND bozo_id in ($del)
EOT;
      $res = mysql_query($query) or
        die(error_page(mysql_error()));
      // remove the username from the session cache

  }
  $bozo_set=get_bozo_set();
}

header("Location: $HTTP_REFERER");

?>

