<? 
#$Id$

require_once("./global.inc");
//
// take care of the id
$chunks = explode(".", $id);
$article_id = $chunks[0];


include_once("Swinsite/Articles.php");
$a = new Articles();
$row = $a->getArticle($article_id,$db);

$a_article_id = $row['article_id'];
$a_user_id    = $row['user_id']; 
$a_username   = $row['username'];
$a_web        = $row['web'];
$a_date       = $row['date'];
$a_status     = $row['status'];
$a_title      = $row['title'];
$a_blurb      = $row['blurb'];
$a_category   = $row['category'];
$a_image      = $row['image'];
$a_text       = $row['text'];
unset($row);

$p_article_id = $a->otherArticleId($a_article_id,$a_user_id,"<",$db);
$n_article_id = $a->otherArticleId($a_article_id,$a_user_id,">",$db);


//
// if they dont have an article id, then
// they should not be here, or their status is 4 (deleted)
if ($status==4) {
  header("Location: ./index.phtml?no_aricle_id");
  exit();
}
if (isset($a_title))
$title = "$a_title by $a_username";
$into_template="insert_article.inc";
// do you have comments?
$into_template2="insert_comments.phtml";
# is rollcall.inc displayed?
# 0 for norollcall.inc; 1 for rollcall.inc.
$rollcall=1;

include_once("./templates/template.inc");

?>
