<? 
#$Id$

require_once("./global.inc");
//
// take care of the id
$chunks = explode(".", $id);
$article_id = $chunks[0];


include_once("Swinsite/Articles.php");
$a = new Articles();
$a->AddHit($db,$article_id);
$row = $a->getArticle($article_id,$db);

$a_article_id = $row['article_id'];
$a_user_id    = $row['user_id']; 
$a_username   = $row['username'];
$a_web        = $row['web'];
$a_date       = $row['date'];
$a_status     = $row['status'];
$a_title      = $row['title'];
$a_blurb      = $row['blurb'];
$a_category   = $row['category'];
$a_image      = $row['image'];
$a_text       = $row['text'];
unset($row);

if ($a_image > 0) {
    $imgurl=IMGURL;
      $query = "SELECT file_id, ext, filename, description 
                FROM articles_files 
                WHERE article_id=$a_article_id 
                ORDER BY file_id";
      $res = mysql_query($query);
      $i=0;
      while ($row = mysql_fetch_row($res)) {

        $file_id   = $row[0];
        $ext       = $row[1];
        $given     = $row[2];
        $desc      = $row[3];
        $img_loc   = $id .'_'. $file_id .'.'. $ext;
        if ($img_names) {
          array_push($img_names, "$img_loc");
        } else {
          $img_names = array("$img_loc");
        }
      }  
  include_once("Swinsite/File.php");
  $f = new File();
  $a_text = $f->regexNames($img_names,$a_text);
}
$p_article_id = $a->otherArticleId($a_article_id,$a_user_id,"<",$db);
$n_article_id = $a->otherArticleId($a_article_id,$a_user_id,">",$db);


//
// if they dont have an article id, then
// they should not be here, or their status is 4 (deleted)
if ($status==4) {
  header("Location: ./index.phtml?no_aricle_id");
  exit();
}
if (isset($a_title))
$title = "$a_title by $a_username";
$into_template="insert_article.inc";
// do you have comments?
$into_template2="insert_comments.phtml";
# is rollcall.inc displayed?
# 0 for norollcall.inc; 1 for rollcall.inc.
$rollcall=1;

include_once("./templates/template.inc");

?>
