
<!-- list of links -->



<table bgcolor=#ffcc00 width=100% heigth=100% border=1 bordercolor=gray>
<tr>
<td>
<a href='#'><strong>News</strong></a>
</td>
</tr>
<tr>
<td>
<a href='#'><strong>A & E</strong></a>
</td>
</tr>
<tr>
<td>
<a href='#'><strong>Body & Soul</strong></a>
</td>
</tr>
<tr>
<td>
<a href='#'><strong>Style</strong></a>
</td>
</tr>
<tr>
<td>
<a href='#'><strong>Society</strong></a>
</td>
</tr>
<tr>
<td>
<a href='#'><strong>Sports</strong></a>
</td>
</tr>
</table>
