<HTML>
<HEAD>
<TITLE>Lifestyles.neopets.com/Categories</TITLE>
<style type="text/css">
<!--
.copy {font-size: 10; font-family: arial; letter-spacing: 2px}
H2 {font-size: 20; font-family: arial; letter-spacing: 5px}
UL LI {list-style: upper-alpha; letter-spacing: 3px; font-family: arial; font-size: 11}
UL UL LI {list-style: upper-roman}
UL UL UL LI {list-style: lower-alpha}
UL UL UL UL LI {list-style: decimal}


-->
</style>
</HEAD>
<BODY>
<H2>LIFESTYLES.NEOPETS.COM</H2>

<UL>
<UL>
<li> BODY & SOUL
	<UL>
	<li>Health Notes
	<li>Happiness Tips
	<li>Features
	<li>Articles
	</UL>
<li> ARTS & ENTERTAINMENT
	<UL>
	<li>Music
	<li>Movies
	<li>TV
	<li>Games
	<li>Books
	</UL>
<li> STYLE & FASHION
	<UL>
	<li>News
	<li>Designers
	<li>Reviews
	<li>Articles
	</UL>
<li> SOCIETY
	<UL>
	<li>News
	<li>Politics
	<li>View Points
	<li>Advice (From Moms and Dads)
	</UL>
<li> SPORTS
	<UL>
	<li>News
	<li>Spotlight
	<li>Fan Clubs
	<li>Betting (NP)
	</UL>
<li> CLUBS
	<UL>
	<li>by School
	<li>by Special Interest
	<li>by User
	</UL>
</UL>

<P class="copy">Copyright (c)  Neopets.com</P>




</BODY>
</HTML>








