<table width="70%">
<tr>
<td>

<p>
<b>what is swinney?</b>
</p>

<p>
the word 'swinney' can be used to refer to two different things:
</p><p>
1. <a href="userpages.phtml?username=austin">austin swinney</a>, the dashing young libra who created swinney.org
</p><p>
or
</p><p>
2. swinney.org, the website where people (humans) write journal
entries (usually text, with occasional images).
</blockquote>
</p><p>
<b>who writes on swinney.org?</b>
</p><p>
anyone! <a href="submit_article.phtml">including you</a>, if you want.
</p><p>
in the past, <a href="roll_call_all.phtml">these people</a> have
written on swinney.org. 
</p><p>
(something here about austin melbs sf)
</p></blockquote>
<p>
<b>do i have to sign up or log in or something?</b>
</p><p>
no, you don't have to sign up. just write a journal entry <a
href="submit_article.phtml">here</a>. if you write more than
once, and use the same name every time, it'll be easier for people to
find what you've written, but it's not a rule or anything.
</p>

<p> <b>what should i write?</b> </p>

<p> anything you want! entries have consisted of anything from bad
haiku to someone's irc chat logs to harrowing tales of near death.
</p>

<p> carefully constructed texts and thoughtful rambles are always
appreciated. you know, <i>writing</i>.  </p>

<p> this isn't a BBS and this isn't a mailing list. posts that make us
feel like this is a BBS or a mailing list might not make it through
our not-so-rigourous editorial process.  Cyantist has a good article
about this: <a
href="http://swinney.org/journals/article.phtml?id=935.txt">who
censor's the censor?</a>

<p> <b>who will read what i write?</b> </p>

<p> no one can really say who reads what on this here
internet. all you can really bet is that some of the people who write
on swinney.org a lot also read swinney.org a lot, so they will
probably read what you write.  </p> 

<p> <b>ok i wrote something, howcome it isn't showing up?</b> </p>

<p> swinney.org has a group of people who "activate" the things you
write so everyone can see them.  </p>

<p>
sometimes the person activating decides what you wrote didn't
have enough content or was a mistaken submission. sometimes we are just lazy and
didn't go and activate the article yet. rarely, but sometimes,
whatever you wrote just gets veto'd for nebulous editorial purposes.  .
</p>
</td>
</tr>
</table>











