<!--
$Id$
-->
<a name="top">
<table cellpadding="0" cellspacing="0" border="0" width="375">
<tr>
<td>
<p class="header"><b>frequently asked questions</b></p>
<p>
<b>general:</b>
</p><p>
<ul>
<li> <a href="#whatis">who or what is swinney.org?</a>
<li> <a href="#whowrites">who writes on swinney?</a>
</ul>
</p><p>
<b>about logging in:</b>
</p><p>
<ul>
<li> <a href="#doi">do i have to sign up or log in or something?</a>
<li> <a href="#whathappens">what happens if i'm logged in and i post an article or comment using a name other than my login name?</a>
</ul>
</p><p>
<b>submitting and editing articles:</b>
</p><p>
<ul>
<li> <a href="#whatshould">what should i write?</a>
<li> <a href="#whowill">who will read what i write?</a>
<li> <a href="#oki">ok i wrote something, howcome it isn't showing up?</a>
<li> <a href="#isubmitted">i submitted something, then i realized i made a big mistake somewhere in the text. what do i do?</a>
<li> <a href="#arethere">are there any HTML guidelines for submissions?</a>
</ul>
</p><p>
<b>categorization, commenting, the bozo list, and leaving</b>:
</p><p>
<ul>
<li> <a href="#somemean">some mean person categorized my beloved article as "gay," when it is most surely not gay and is, in fact, a serious work of art. how can i rectify this situation???</a>
<li> <a href="#howcome">how come i commented on something and it was there, but then disappeared?</a>
<li> <a href="#someoneon">someone on the site annoys me. what can i do?</a>
<li> <a href="#removeme">i'm done with you people, can you remove all traces of me from the site?</a>
</ul>
</p>
</p>
<P><B>odds and ends:</b>
</P><P>
<UL>
<LI> <A href="#lol">OMG, LOL, what?</A>
</UL>


<p>
<b>credits and contact:</b>
</p><p>
<ul>
<li> <a href="#whobrought">who brought this work to me?</a>
<li> <a href="#forgeneral">for general assistance and inquiries</a>
</ul>
<p>...</p>

<p class="header">general:</p>

<a name="whatis">
<p class="subheader"><b>who or what is swinney.org?</b></p>

<BLOCKQUOTE><i>
Swinney.org provides an outlet of sorts to kindred
spirits across this land. Those creative souls that feel the
darkness of jobs, school and oppressive family units bearing
down on them at all times.<BR>--wb, <a href="./usercomments.php?username=wb">swinney.org's critic</a>
</I></BLOCKQUOTE>


<p>
the word 'swinney' can be used to refer to a few different things:
</p>

<p>
<OL>
<LI><a href="userpages.php?username=austin">austin swinney</a>, the dashing young libra who created swinney.org, or;

<br>
<br>

<LI>swinney.org, the website where people (humans) write articles
 (usually text, with occasional images), or;

<br>
<br>

<LI>one who belongs to the family of writers on swinney.org.
<br>
<br>
<li>an article written on swinney.org. usage: <i>i just wrote a swinney</i>.

</OL>
</p>

<p align="right"><font size="1"><a href="#top">back to top</a></font></p>
<a name="whowrites">
<p class="subheader"><b>who writes on swinney.org?</b></p>
<p>
anyone! <a href="submit_article.php">including you</a>, if you want.
</p>

<p>
in the past, <a href="roll_call_all.php">these people</a> have
written on swinney.org. 
</p>
<p align="right"><font size="1"><a href="#top">back to top</a></font></p>

<p class="header">about logging in:</p>

<a name="doi">
<p class="subheader"><b>do i have to sign up or log in or something?</b></p>
<p>
yes, you have to have an account on swinney.org to write here. after you've <a href="/journals/submit_register.php">registered</a>, just <a
href="submit_article.php">submit an article here</a>. 
</p>
<p align="right"><font size="1"><a href="#top">back to top</a></font></p>
<a name="whathappens">
<p class="subheader"><b>what happens if i'm logged in and i post an article or comment using a name other than my login name?</b></p>
<p>if you do that, whatever other names you use in the various 'name' input boxes will be listed as your alias, but all will be associated with your login name.</p>
<p>it might be wise to write all your articles using the same name, because it makes it easier for you to link to all your swinney articles at once from elsewhere. it also makes it easier for people to find your writing on the site.
</p>
<p align="right"><font size="1"><a href="#top">back to top</a></font></p>

<p class="header">submitting and editing articles:</p>
<a name="whatshould">
<p class="subheader"><b>what should i write?</b></p>

<p> 
anything you want! articles have consisted of anything from bad
haiku to someone's irc chat logs to harrowing tales of near death.
</p>

<p> 
carefully constructed texts and thoughtful rambles are always
appreciated. you know, <i>writing</i>.  
</p>

<p> 
this isn't a BBS and this isn't a mailing list. articles that make us
feel like this is a BBS or a mailing list might not make it through
our not-so-rigorous editorial process.  swinney user cyantist wrote a good article
about this: <a
href="http://swinney.org/journals/article.php?id=935.txt">who
censors the censor?</a>
</p>
<p align="right"><font size="1"><a href="#top">back to top</a></font></p>
<a name="whowill">
<p class="subheader"><b>who will read what i write?</b></p>

<p> no one can really say who reads what on this here internet, though
<a href="http://stats.saturn5.com/swinney.org/">there are
stats</a>. all you can really bet is that some of the people who write
on swinney.org a lot also read swinney.org a lot, so they will
probably read what you write.  </p>
<p align="right"><font size="1"><a href="#top">back to top</a></font></p>
<a name="oki">
<p class="subheader"><b>ok i wrote something, how come it isn't showing up?</b></p>

<p>
swinney.org has a group of people who "activate" the things you
write so everyone can see them.
</p>

<p>
sometimes the person activating decides what you wrote didn't
have enough content or was a mistaken submission. sometimes we are just lazy and
didn't go and activate the article yet. rarely, but sometimes,
whatever you wrote just gets vetoed for nebulous editorial purposes.
</p>
<p align="right"><font size="1"><a href="#top">back to top</a></font></p>
<a name="isubmitted">
<p class="subheader"><b>i submitted something, then i realized i made a big mistake somewhere in the text. what do i do?</b></p>
<p>login and click on settings. click on "edit article" on the settings page. here is a <a href="http://swinney.org/journals/vip/edit_article.php">direct link</a> to that page. in this area you are able to make whatever edits you want to the last article you submitted, whether it's been activated by an editor already or not.
</p>
<p align="right"><font size="1"><a href="#top">back to top</a></font></p>
<a name="arethere">
<p class="subheader"><b>are there any HTML guidelines for submissions?</b></p>
<p>not really, but le's pet peeve is when people use a single &lt;BR&gt; instead of a double break to indicate a new paragraph. it also bugs her when people don't close their &lt;p&gt; tags. now, there was a time when she also didn't close her &lt;p&gt tags, so it's not that she doesn't relate, it's just that she's seen the light now. </p>
<p align="right"><font size="1"><a href="#top">back to top</a></font></p>
<p class="header">categorization, commenting, and the bozo list</p>
<a name="somemean">
<p class="subheader"><b>some mean person categorized my beloved article as "gay," when it is most surely not gay and is, in fact, a serious work of art. how can i rectify this situation???</b></p>
<p>any article can be recategorized by entering the article number (found in the URL of the article) into the URL of the categorization page. for example:<br><br>
<tt>
http://swinney.org/journals/submit_category.php?id=000
</tt>
</p><p>
in the above url, change "000" to the number of your article.
</p>
<p align="right"><font size="1"><a href="#top">back to top</a></font></p>
<a name="howcome">
<p class="subheader"><b>how come i commented on something and it was there, but then disappeared?</b></p>

<p>
swinney.org is not a place to come if you define yourself by the
ability to kick others down, or kick them when they are down.  also,
dont come here to be annoying.  be thoughtful.  be challenging.  do
not be a prick.  this site is moderated by a hand full of fair people
who are not annoying or mean.  if your comment was removed and you feel
it was done so unjustly, email <a
href="mailto:editorsNO@SPAMswinney.org">editorsNO@SPAMswinney.org</a>.
</p>

<p>
see <a href="article.php?id=1223.txt">energy monsters, or how the F.O.L.K. wars have changed</a> by one of our resident moms, <a href="userpages.php?username=auntie">auntie</a>.
</p>

<p align="right"><font size="1"><a href="#top">back to top</a></font></p>
<a name="someoneon">
<p class="subheader"><b>someone on the site annoys me. what can i do?</b></p>
<p>if someone is a clown, you can add them to your bozo list. to do so, just click on their name in the comment area, which will bring up a little page about them. on that page, click "add to bozolist." if they deserve forgiveness later, you can remove them by clicking "Edit Bozolist" in the "settings" area.</p><p>you must be logged in to use the bozolist.
</p>

<p align="right"><font size="1"><a href="#top">back to top</a></font></p>
<a name="removeme">
<p class="subheader"><b>i'm done with you people, can you remove all traces of me from the site?</b></p>
<P>no, this site does not do that.  if you wrote here and now you want to leave, just leave.  eventually anything you wrote here will be burried.  if you created some drama in your life by writing here, take a few deep breaths and keep in mind the internet does not matter.  please come back whenever you feel like it.</P>

<p align="right"><font size="1"><a href="#top">back to top</a></font></p>

<p class="header">odds and ends:</p>
<a name="lol">
<P class="subheader"><B>OMG, LOLZ, what?</B></P>
<P>we all love internet acronyms, but don't put them in your article.</P>

<p align="right"><font size="1"><a href="#top">back to top</a></font></p>



<p class="header">credits and contact:</p>

<a name="whobrought">
<p class="subheader"><B>who brought this wonder to me?</B></P>

<P>austin swinney of <a href="http://swinney.org">swinney.org</a> wrote the initial code and continues to suck and evade responsibilities in a never ending quest remain a child.</P>

<P>peter rhodamine of <a href="http://citynoise.org">citynoise.org</a> is the managing editor and likes to use this website to stock his harem with wives not leaving any girls for the rest of us.  he uses the thoughts section to wage passive aggressive arguements with his beautiful wife.

<P>brian moseley of <a href="http://www.maz.org">maz.org</a> is the dungeon master who runs <a href="http://warhorn.net">war horn</A> and has made significant code rewrites and contributions to the arts and humanities, without whom, there would be no dreams come true.  when he blows his horn, we go to battle.</P>

<P> jim home of <a href="http://thisishomemade.com">thisishomemade.com</a> did the design of "<a href="http://swinney.org/journals/article.php?id=1869">Ye Olde Swinney</a>", as well as some code.  he does yoga with his wife (in bed), and makes <a href="http://www.longbets.org/">long bets</a>.</P>

<P>_(pa[nic)k] pwnz, womanizes, and operates <a href="http://farc.ikami.com/">the internet whore house</a> upon which this twitchy trigger finger of the revolucion resides.  women run from him.  men race him.  austin and simon steal his car when he passes out.</P>

<P>elly millican of <a href="http://www.elly.org">elly.org</a> rewords this FAQ.  she is a coyote trickster.  for a brief while, she worked at a soap store and never smelled so good.  she has since moved to the <a href="http://eff.org">frontier</a> never to be seen again.</P>

<P>DA OLSEN TWINZZ OWN UR SHIT1!11!!! LOLZ WTF</P>

<P>you are welcome to help.</P>

<p align="right"><font size="1"><a href="#top">back to top</a></font></p>
<a name="forgeneral">
<p class="subheader"><b>for general assistance with this site, inquiries:</b></p>
<P>the swinney.org editorial staff<BR>
<a href="mailto:editorsNO@SPAMswinney.org">editorsNO@SPAMswinney.org</a></P>

<p align="right"><font size="1"><a href="#top">back to top</a></font></p>



</td>
</tr>
</table>










