<table width="70%">
<tr>
<td>
<h2>Frequently Asked Questions</h2>
<h3>what is swinney?</h3>

<p>
the word 'swinney' can be used to refer to two different things:
</p><p>
<OL>
<LI><a href="userpages.phtml?username=austin">austin swinney</a>, the dashing young libra who created swinney.org
</p><p>
or
</p><p>
<LI>swinney.org, the website where people (humans) write journal
entries (usually text, with occasional images).
</blockquote>
</OL>
</p>
<h3>who writes on swinney.org?</h3>
<p>
anyone! <a href="submit_article.phtml">including you</a>, if you want.
</p><p>
in the past, <a href="roll_call_all.phtml">these people</a> have
written on swinney.org. 
</p></blockquote>
<h3>do i have to sign up or log in or something?</h3>
<p>
no, you don't have to sign up. just write a journal entry <a
href="submit_article.phtml">here</a>. if you write more than
once, and use the same name every time, it'll be easier for people to
find what you've written, but it's not a rule or anything.
</p>

<h3>what should i write?</h3>

<p> anything you want! entries have consisted of anything from bad
haiku to someone's irc chat logs to harrowing tales of near death.
</p>

<p> carefully constructed texts and thoughtful rambles are always
appreciated. you know, <i>writing</i>.  </p>

<p> this isn't a BBS and this isn't a mailing list. posts that make us
feel like this is a BBS or a mailing list might not make it through
our not-so-rigourous editorial process.  Cyantist has a good article
about this: <a
href="http://swinney.org/journals/article.phtml?id=935.txt">who
censor's the censor?</a>

<h3>who will read what i write?</h3>

<p> no one can really say who reads what on this here
internet. all you can really bet is that some of the people who write
on swinney.org a lot also read swinney.org a lot, so they will
probably read what you write.  </p> 

<h3>ok i wrote something, howcome it isn't showing up?</h3>

<p> swinney.org has a group of people who "activate" the things you
write so everyone can see them.  </p>

<p>
sometimes the person activating decides what you wrote didn't
have enough content or was a mistaken submission. sometimes we are just lazy and
didn't go and activate the article yet. rarely, but sometimes,
whatever you wrote just gets veto'd for nebulous editorial purposes.  .
</p>


<h3>how come i commented on something and it was there, but then disappeared?</h3>

<P>swinney.org is not a place to come if you define yourself by the
ability to kick others down, or kick them when they are down.  also,
dont come here to be annoying.  be thoughtful.  be challenging.  do
not be a prick.  this site is moderated by a hand full of fair people
who are not annoying or mean.  if your comment was removed and you feel
it was done so unjustly, email <a
href="mailto:editors@swinney.org">editors@swinney.org</a>.</P>

<P>see <a href="article.phtml?id=1223.txt">energy monsers, or how the F.O.L.K. wars have changed</a> by one of our resident moms, <a href="userpages.phtml?username=auntie">auntie</a>.

<h3>for general assistance with this site, inqueries:</B></P>
<P>austin swinney<BR>
austin@swinney.org<BR>
santa cruz, CA, US</P>
<P>Fri Jul 13, 2001 12:22 PM</P>
</td>
</tr>
</table>











