

<HTML>
<HEAD>
<TITLE>swinney.org</TITLE>
<META NAME="keywords" CONTENT=" Austin Swinney ;">
<STYLE TYPE="text/css">
<!--
p {  font-family: Arial, Helvetica, sans-serif; font-size: 10pt} 
/* so I don't have to fuck with font tags */
pre { color: navy } 
/* predefined colr name */
-->
</STYLE>
</HEAD>
<BODY BGCOLOR="#DED3D3" LINK="red">

<?
  // Include the global.inc file
  // $WWW_ROOT = "/home/1/aswinney/swinney.org/journals";
  include "global.inc";
?>
