
<?

include "connect.inc";


// what table are you paginating?
$table="comments";

// what page would you like to return?
$return="comments";

//No Page Number? Set it to Page 1 then
if(!$page_num || $page_num < 1) { 
        $page_num = 1;
}

//How many pages per page will be displayed...
$per_page = 20;

//Set the page start variable...
$page_start = ($page_num-1) * $per_page;


 
//Do a number query to see how many results match the category...
$num_res = mysql ("$DB", "SELECT count(*) as num_articles FROM $table WHERE status='0' ORDER BY timestamp DESC");
$num_object = MYSQL_FETCH_OBJECT($num_res);
$num_of_results = $num_object->num_articles;

$res = mysql ("$DB", "SELECT * FROM $table WHERE status='0' ORDER BY timestamp DESC limit $page_start,$per_page");

// Find out how many pages there are going to be
// number of results returned divided by the number per page displayed
$num_of_pages = $num_of_results/$per_page; 

// Find out if the num_of_pages was a decimal.. Can't have 2.1 pages...
$remainders = $num_of_results%$per_page; 


if($remainders != 0){ //If is was a decimal, turn it into an integer and add 1 to it...
       $num_of_pages = intval($num_of_pages) + 1;
}

$page_back = $page_num - 1;
$page_forward = $page_num + 1;


//while ($row = mysql_fetch_object($res)) {
if (isset($res)) {

$url = "article.phtml?id=$d->article_id";



   echo "<P>";

     if($page_num == 1){
            print "<PRE><b><<</b> <a href='submit_article.phtml'><strong>I want to write</strong></a>";
     }


     if($page_num > 1){
	     print "<PRE><a href=\"$return.phtml?&page_num=$page_back\"><b><<</a></b> <a href='submit_article.phtml'><strong>I want to write</strong></a>";


     } 

  
     if($page_num < $num_of_pages) { 
             print " <a href=\"$return.phtml?page_num=$page_forward\"><b>>></b></a></PRE>";
     } 

     if($page_num == $num_of_pages) {
             print "<b>>></b></PRE>";
     }

 echo "</P>";

}

// comments.inc


// this is set to determine header() in process_edit_comments.phtml

echo "<!-- previous: $previous -->\n";

while ( $d = mysql_fetch_object ($res) ) {
$comment_id = $d->comment_id;
$username = $d->username;
$comment = $d->comment;
$article_id = $d->article_id;

$res2 = mysql("$DB", "SELECT username,title FROM pending_articles WHERE article_id=$article_id");
$row = mysql_fetch_row($res2);

echo "<TABLE border=1 cellspacing=0 cellpading=0 width='100%'>";
echo "<TR><TD valign='top' bgcolor=#999999>\n";
echo "$username on \"<a href='article.phtml?id=$article_id.txt#$comment_id'>$row[1]</A>\" by <a href='userpages.phtml?username=$row[0]'>$row[0]</a></TD></TR>";
echo "<TR><TD>".stripslashes($comment)."</TD></TR></TABLE>";

}
?>




































