
<!-- here is where we voice our ideas.  raise you hands and i'll call on you in order. -->

<?
$query = "SELECT * FROM thoughts ";
if ($bozo_set && $bozo_set!="") {
  if ($bozo_set=="()") {
      $bozo_set=get_bozo_set();
  }
  $query .= " WHERE user_id NOT IN $bozo_set ";
}
if ($insert_since) {
  if (!$bozo_set) {
      $query .= " WHERE";
  } else {
      $query .= " AND";
  }
  $query .= " timestamp > $insert_since ";
}
$query .=" ORDER BY comment_id DESC LIMIT 5";
$res = mysql_query ($query) or die($query);

// multiple rows 
while ( $d = mysql_fetch_object( $res ) ) {

// move it to strip slashes
$username=$d->username;
$thought=$d->thought;

// echo and strip

$username=stripslashes($username);
$thought=eregi_replace("bus","dong",stripslashes($thought));
$ext = substr($thought,-3);

if ($ext == "jpg"||$ext == "JPG"||$ext == "gif"||$ext == "png") {

echo <<<EOT
<tr>\n
<td colspan=3 align="center" class="thoughts"><IMG SRC="$thought" ALT="$username"></td>\n
<tr>
EOT;

} else {

echo "<tr>\n<td align=\"right\" valign=\"top\" class=\"thoughts\" nowrap>\n$username</td>\n\n<td valign=\"top\" class=\"thoughts\" nowrap>\n&nbsp;.o0O</td>\n\n<td valign=\"top\" class=\"thoughts\">\n($thought)</td>\n</tr>\n\n";
   }
}
?>






