<?
// -*- Mode: PHP; indent-tabs-mode: nil; -*-
// $Id$

$article_id = explode (".", $article_id);
$basename = $article_id[0];

echo <<<EOT
<!-- 
here is where we voice our ideas.  raise you hands and ill call on you
in order.
-->

<p align="center">
<a href="submit_comment.phtml?article_id=$basename" accesskey="s">
comment</a>
</p>

EOT;

$query = <<<EOT
  SELECT username,comment_id,comment
    FROM comments
   WHERE article_id=$basename
     AND status=0 
EOT;
if (count($bozos)) {
  $query .= " AND username NOT IN $bozo_set";
}
if ($insert_since) {
  $query .= " AND timestamp > $insert_since";
}
$query .= <<<EOT
ORDER BY comment_id
EOT;

$res = mysql_query ($query);

while ($d = mysql_fetch_object($res)) {
  $username = stripslashes($d->username);
  $comment = stripslashes($d->comment);

  // LULU MADNESS
  if ($username == "lulu") {
    $username = "<span style=\"background-color:pink\">$username"; 
    $comment = "$comment</span>";
  }

  echo <<<EOT
<br>
<p>
<a name="$d->comment_id">$username:</a>
$comment
</p>

EOT;
}

if (mysql_num_rows($res) >= 5) {
  echo <<<EOT
<br>
<p align="center">
<a href="submit_comment.phtml?article_id=$basename" accesskey="s">
comment</a>
</p>

EOT;
}

?>
