<HTML>
<HEAD>
<TITLE>mind reader</TITLE>
</HEAD>
<BODY bgcolor="black">


<!-- here is where we voice our ideas.  raise you hands and i'll call on you in order. -->


<?

 include "connect.inc";

/*
mysql> describe thoughts;
+------------+---------------+------+-----+-------------+----------------+
| Field      | Type          | Null | Key | Default     | Extra          |
+------------+---------------+------+-----+-------------+----------------+
| comment_id | int(11)       |      | PRI | 0           | auto_increment |
| timestamp  | timestamp(14) | YES  |     | NULL        |                |
| username   | varchar(20)   | YES  |     | nappy_sucka |                |
| thought    | text          | YES  |     | NULL        |                |
+------------+---------------+------+-----+-------------+----------------+
*/
$article_id = explode (".", $article_id);

$no_extension = $article_id[0];

$res = mysql ("swinney","SELECT * FROM thoughts ORDER BY timestamp DESC");

// multiple rows 
while ( $d = mysql_fetch_object( $res ) ) {

// move it to strip slashes
$username=$d->username;
$thought=$d->thought;

// echo and strip

echo "<font color='red'><strong>";
echo stripslashes($username)."</strong></font>";
echo "<font color='FF9966'>";
echo " .o0O(".stripslashes($thought).")\n";
echo "</font><br>\n"; 
}

?>

</BODY>
</HTML>





