

<!-- here is where we voice our ideas.  raise you hands and i'll call on you in order. -->


<?

/*
mysql> describe thoughts;
+------------+---------------+------+-----+-------------+----------------+
| Field      | Type          | Null | Key | Default     | Extra          |
+------------+---------------+------+-----+-------------+----------------+
| comment_id | int(11)       |      | PRI | 0           | auto_increment |
| timestamp  | timestamp(14) | YES  |     | NULL        |                |
| username   | varchar(20)   | YES  |     | nappy_sucka |                |
| thought    | text          | YES  |     | NULL        |                |
+------------+---------------+------+-----+-------------+----------------+
*/
$article_id = explode (".", $article_id);

$no_extension = $article_id[0];

$res = mysql ("$DB","SELECT * FROM thoughts ORDER BY comment_id DESC LIMIT 5");
echo "<P>";
// multiple rows 
while ( $d = mysql_fetch_object( $res ) ) {

// move it to strip slashes
$username=$d->username;
$thought=$d->thought;

// echo and strip

echo stripslashes($username);
echo " .o0O(".stripslashes($thought).")<BR>\n";

}
echo "</P>";
?>






