<?
include "global.inc";
include "connect.inc";
echo "$username\n";
echo "$password\n";

$res = mysql("$DB", "SELECT username,password FROM users WHERE username='$username' AND password='$password'");

if (!$res) {
echo "Sorry, $username but you are going to have to register that.";
}

//user_set_tokens($username_in);
setcookie('username',$username,(time()+2592000),'/','',0);



//header("Location:$HTTP_REFERER");
?>



