<?

include "connect.inc";


/*
mysql> describe thoughts;
+------------+---------------+------+-----+-------------+----------------+
| Field      | Type          | Null | Key | Default     | Extra          |
+------------+---------------+------+-----+-------------+----------------+
| comment_id | int(11)       |      | PRI | 0           | auto_increment |
| timestamp  | timestamp(14) | YES  |     | NULL        |                |
| username   | varchar(20)   | YES  |     | nappy_sucka |                |
| thought    | text          | YES  |     | NULL        |                |
+------------+---------------+------+-----+-------------+----------------+
*/

$article_id = explode (".", $article_id);

$article_id = $article_id[0];

// echo "$article_id";

  if ( $username == "name" ) {
    echo ("Names don't think, back up and try again.");
    exit;
  }
  if ( $thought == "thought" ) {
    echo ("To thought, you must think.  Back up and try again.");
    exit;
  }
  if ( $username == "" ) {
    echo("There are many names for nothing, you just found one.  Back up and try again.");
    exit;
  }
  if ( $thought == "" ) {
    echo("In nothing, there exists blankness.  Back up and try again.");
    exit;
  }

// echo "$username<br>$comment<br>$nature<br>";

$res = mysql("$DB","INSERT INTO thoughts VALUES (NULL, NULL,'".addslashes($username)."','".addslashes($thought)."')"); 

  if ( $res == false ) { 
    echo ("Bollocks!");
    exit;
  }
//  mail("thoughts@swinney.org", "comment: $username",  "$thought"); 
header("Location: http://swinney.org");
?>







