<?

include "global.inc";

  if ( $username == "" ) {
    echo "This username is not set";
    exit;
  }


/*
mysql> describe links;
+-------------+---------------+------+-----+---------+----------------+
| Field       | Type          | Null | Key | Default | Extra          |
+-------------+---------------+------+-----+---------+----------------+
| 1 link_id   | int(11)       |      | PRI | 0       | auto_increment |
| 2 username  | varchar(20)   | YES  |     | NULL    |                |
| 3 timestamp | timestamp(12) | YES  |     | NULL    |                |
| 4 status    | tinyint(4)    | YES  |     | NULL    |                |
| 5 title     | varchar(50)   | YES  |     | NULL    |                |
| 6 url       | varchar(255)  | YES  |     | NULL    |                |
| 7 blurb     | varchar(255)  | YES  |     | NULL    |                |
| 8 category  | int(20)       | YES  |     | NULL    |                |
+-------------+---------------+------+-----+---------+----------------+
*/

echo   "database: $DB<BR>
	username: $username<BR>
	title: $title<BR>
	URL: <a href=\"$url\">$url</a><BR>
	blurb: $blurb<BR>
	category_id: $category_id<BR><BR>";

// Insert into the database

$res = mysql_query ( "INSERT INTO links SET 
username='$username',
status=0,
title='$title',
url='$url',
blurb='$blurb',
category=$category");

$error=mysql_error();
echo "$error";

  if ( $res == false ) { 
    echo("Bullocks!");
    exit;
  }

 mail("links@swinney.org", "$title by $username", "$title\n$blurb\n$url");
 header("Location:links.phtml" ); 

?>








































