<?


    include "connect.inc";
  // Init the date and time
  $date = date("Y-m-d");
  $time = time();

  if ( $username == "" ) {
    error("This username is not set");
    exit;
  }
 
  // Work out what subjects
  $res = mysql("", "SELECT MAX(category_id) FROM categories");
  $maxid = mysql_result($res, 0, 0);
  $subject_value = 0;
  for ( $i = 1 ; $i <= $maxid ; $i++ ) {
    $str = "cat".$i;
    if ( $$str == "on" ) {
      $val = pow(2, $i-1);
      $subject_value += $val;
    }
  }


  // Insert into the database
/*
mysql> describe links;
+-------------+---------------+------+-----+---------+----------------+
| Field       | Type          | Null | Key | Default | Extra          |
+-------------+---------------+------+-----+---------+----------------+
| 1 link_id   | int(11)       |      | PRI | 0       | auto_increment |
| 2 username  | varchar(20)   | YES  |     | NULL    |                |
| 3 timestamp | timestamp(12) | YES  |     | NULL    |                |
| 4 status    | tinyint(4)    | YES  |     | NULL    |                |
| 5 title     | varchar(50)   | YES  |     | NULL    |                |
| 6 url       | varchar(255)  | YES  |     | NULL    |                |
| 7 blurb     | varchar(255)  | YES  |     | NULL    |                |
| 8 category  | int(20)       | YES  |     | NULL    |                |
+-------------+---------------+------+-----+---------+----------------+
*/

  $res = mysql	 ("", "INSERT INTO links VALUES ( 
	'NULL', 
	'$username', 
        'NULL',
	'1', 
	'".addslashes($title)."',
        '$url',
	'".addslashes($blurb)."', 
	'$category',
	)");

  if ( $res == false ) { 
    echo("Bullocks!");
    exit;
  }


 mail("article@swinney.org", "$title by $username", "$title\n$blurb\n$url");
 header("Location:index.phtml" ); 

?>








































