<?
include "global.inc";

/*
+------------+---------------+------+-----+-----------+----------------+
| Field      | Type          | Null | Key | Default   | Extra          |
+------------+---------------+------+-----+-----------+----------------+
| comment_id | int(11)       |      | PRI | NULL      | auto_increment |
| article_id | int(11)       |      |     | 0         |                |
| timestamp  | timestamp(12) | YES  |     | NULL      |                |
| username   | varchar(255)  | YES  |     | anonymous |                |
| comment    | text          | YES  |     | NULL      |                |
| nature     | int(4)        | YES  |     | NULL      |                |
| status     | int(4)        | YES  |     | 0         |                |
| ip_addr    | text          | YES  |     | NULL      |                |
+------------+---------------+------+-----+-----------+----------------+
*/

// get the users ip address.  maybe this is uncool, but i think it is a
// necessary precaution.  like dont i want to know who the person is who
// tries to send malicious unix commands in to the thoughts database?

$ip_addr = getenv ("REMOTE_ADDR"); // get the ip number of the user

$article_id = explode (".", $article_id);

$article_id = $article_id[0];

// echo "$article_id";

  if ( $username == "" ) {
    echo("You are not allowed to be a nobody on Swinney.org.  Please back up and try entering your name.");
    exit;
  }

  if ( $username == "name" ) {
     echo("Names are nice, but you should get your own.  Please back up and try again.");
     exit;
  }

  if ( $comment == "" ) {
     echo("Commenting on this site is not like some other cultures.  Less is not more.  Please back up and try again.");
     exit;
  }

  if ( $comment == "comment" ) {
     echo("Please speak louder, I can't here you.  Back up and try again.");
     exit;
  }

// echo "$username<br>$comment<br>$nature<br>";

$res = mysql("$DB","INSERT INTO comments VALUES (NULL,'".addslashes($article_id)."',NULL,'".addslashes($username)."','".addslashes($comment)."','".addslashes($nature)."','0','$ip_addr')"); 

  if ( $res == false ) { 
    echo ("Bollocks!");
    exit;
  }



// mail("theCommentator@swinney.org", "comment: $username on $article_id", "$nature", "$comment"); 
header("Location: article.phtml?id=$article_id.txt")
?>










