<?
#$Id$

# fuck this header bullshit, how bout i just loop this shit in with the other shit.

include "global.inc";
/*
+------------+---------------+------+-----+-----------+----------------+
| Field      | Type          | Null | Key | Default   | Extra          |
+------------+---------------+------+-----+-----------+----------------+
| comment_id | int(11)       |      | PRI | NULL      | auto_increment |
| article_id | int(11)       |      |     | 0         |                |
| timestamp  | timestamp(12) | YES  |     | NULL      |                |
| username   | varchar(255)  | YES  |     | anonymous |                |
| comment    | text          | YES  |     | NULL      |                |
| nature     | int(4)        | YES  |     | NULL      |                |
| status     | int(4)        | YES  |     | 0         |                |
| ip_addr    | text          | YES  |     | NULL      |                |
+------------+---------------+------+-----+-----------+----------------+
*/

// get the users ip address.  maybe this is uncool, but i think it is a
// necessary precaution.  like dont i want to know who the person is who
// tries to send malicious unix commands in to the thoughts database?

// get the ip number of the user
$ip_addr = getenv ("REMOTE_ADDR"); 

$article_id = explode (".", $article_id);

$article_id = $article_id[0];

// echo "$article_id";

  if ( $username == "" ) {
      $error_msg = "No one's a nobody on Swinney.org.  Enter your name.";
      session_register("error_msg");
      include("./submit_comment.phtml");
  }

  if ( $username == "name" ) {
      $error_msg = "Names are nice, but you should get your own.";
      session_register("error_msg");
      include("./submit_comment.phtml");
  }

  if ( $comment == "" ) {
      $error_msg = "Please speak louder, I can't hear you.";
      session_register("error_msg");
      include("./submit_comment.phtml");
  }

  if ( $comment == "comment" ) {
      $error_msg = "Commenting on this site is not like some other cultures.  Less is not more.";
      session_register("error_msg");
      include("./submit_comment.phtml");
  }

// echo "$username<br>$comment<br>$nature<br>";

$query="INSERT INTO comments VALUES (NULL,'".addslashes($article_id)."',NULL,'".addslashes($username)."','".addslashes($comment)."','".addslashes($nature)."','0','$ip_addr')";
$res = mysql_query($query); 

  if ( $res == false ) { 
    echo ("Bollocks!");
    exit;
  }

// mail("theCommentator@swinney.org", "comment: $username on $article_id", "$nature", "$comment"); 
header ("Location: article.phtml?id=$article_id.txt");

?>










