<?
// #########################################################
// # $Id$
// # process the submitted registration form, adding a user record to
// # the database, including the ip address so we can track yahoos

require_once("./global.inc");

// make sure a username was submitted
if ($username) {
  // check to see if the username is taken
  $query = "SELECT username FROM user WHERE username='$username'";
  $res = mysql_query($query) or
    die(error_page("database error for query $query: " . mysql_error()));
  $matches = mysql_num_rows($res);

  if (! $matches) {
    // make sure the password and a confirmation were submitted
    if ($password && $password2) {
      // make sure the password and confirmation match
      if ($password == $password2) {
        // add the user to the database
        $ip_addr = getenv("REMOTE_ADDR"); 
        $encrypted_password = crypt($password);
        $query =
          "INSERT INTO user (username,password,email,ip_addr) 
           VALUES ('$username','$encrypted_password','$email','$ip_addr')";

        $res = mysql_query($query) or
          die(error_page("database error for query $query: " . mysql_error()));
        // log the user in and store some info in the session
        $user_id = mysql_insert_id();
        session_register("user_id");

        $authenticated_username = $username;
        session_register("authenticated_username");
      } else {
        $error_msg = "Those passwords don't match.  Try again:";
      }
    } else {
      $error_msg = "You must provide a password and confirm it. Try again:";
    }

  } else {
    $rand = dice(1,99);
    $username = "${username}_likes_ham$rand";
    $error_msg = "Username taken. Swinney suggests:";
  }
} else {
  $username = "SucksEggs" . dice(1,99) . dice(1,99);
  $error_msg = "You must provide a username. Swinney suggests:";
}

if ($error_msg) {
  include("./submit_register.phtml");
} else {
  header("Location: " . URLBASE);
}

?>
