<?
// $Id$
session_register("bin");
require_once("global.inc");

$bin=0;
// Init the date and time
$date = date("Y-m-d");
$time = time();

// Work out what subjects

foreach ($cat as $one => $two) {
   if (!isset($bin)) {
     $bin=$two;
     echo "starting with: ". bin(32,$bin) . "<BR><HR>";
   } else {
     echo bin(32,$bin) ." <BR> ". bin(32,$two) . "<BR>";
     $bin=$bin|$two;
#        echo bin(32,$bin);
	echo bin(32,$bin) ."<BR>";
        echo "<HR>";
   }
}
$bin=0;

/*
if ($username) {
  $ip_addr = getenv ("REMOTE_ADDR");

  // Insert into the database
  $esc_keywords = addslashes($keywords);
  $esc_title = addslashes($title);
  $esc_blurb = addslashes($blurb);

  $query = <<<EOT
INSERT INTO articles_info
    SET
     username='$username',
     web='$web',
     date='$date',
     time='$time',
     status=1,
     keywords='$esc_keywords',
     title='$esc_title',
     blurb='$esc_blurb',
     category='$category',
     image='$image',
     ip_addr='$ip_addr'
EOT;

  if (mysql_query($query)) { 
    $article_id = mysql_insert_id();
    $esc_content = addslashes($content);

    $query = <<<EOT
INSERT INTO articles_text
     VALUES ($article_id, '$esc_content');
EOT;

    if (mysql_query($query)) {
      $success_msg = "Article saved.";
    } else {
      $error_msg = "Problem saving the article text: " . mysql_error();
    }
  } else {
    $error_msg = "Problem saving the article info: " . mysql_error();
  }
} else {
  $error_msg = "You must specify a username.";
}

if ($error_msg) {
  session_register("error_msg");
  include("./submit_article.phtml");
} else {
  session_register("success_msg");

  if ($images_too=="no") {
    $loc = URLBASE;
  } else {
    $loc = "submit_image.phtml?article_id=$article_id";
  }

#  header("Location: $loc");
}
*/
?>
