<?
#$Id$
require_once("global.inc");

if ($username && $password) {
  // pull user info from the database
  $query = <<<EOT
SELECT username, password
  FROM user
 WHERE username='$username'
EOT;

  $res = mysql_query($query)or
    die(error_page(mysql_error()));
  $user = mysql_fetch_object($res);

  // make sure the user exists
  if ($user) {
    // verify the submitted credentials
    if (crypt($password, $user->password) == $user->password) {
    } else {
      $error_msg = "Password mismatch";
      $error_redirect = "login.phtml";
    }
  } else {
    // username does not exist in the database
    $error_msg =
      "Sorry, $username but you are going to have to register that.";
    $error_redirect = "submit_register.phtml?username=$username";
  }
} else {
  $error_msg = "You must specify both a username and a password.";
  $error_redirect = "login.phtml";
}

if ($error_msg) {
  session_register("error_msg");
  header("Location: $error_redirect");
  exit;
}

// save the username in the session so other pages can access it later
// in the session
$authenticated_username = $user->username;
session_register("authenticated_username");

// $back_to is the location where the user originally clicked the "log
// in" link
session_unregister("back_to");
header("Location: " . $back_to);
?>

