<?
// $Id$
require_once("global.inc");

if (!isset($index)) {
  $index = 1;
} else { 
  $index++;
}

if ($submit_image) {
  if (ereg("\.(.+$)", $userfile_name, $matches)) {
    $ext = strtolower($matches[1]);
    $filename = $article_id . "_" . $index . "." . $ext;
  } else {
    $filename = $article_id . "_" . $index;
  }

  // Copy the file to our uploads directory
  if (move_uploaded_file($userfile,
                        DIRBASE . "/journals/images/$filename")) {
    $success_msg = "Image saved.";
  } else {
    $error_msg = "Error saving image.";
  }

  include("./submit_image.phtml");
} else {
  header("Location: " . URLBASE);
}

?>
