<?
// $Id$

require_once("./global.inc");

if ($username && $password) {
  // pull user info from the database
  $query = <<<EOT
SELECT user_id, username, password
  FROM user
 WHERE username='$username'
EOT;

  $res = mysql_query($query)or
    die(error_page(mysql_error()));
  $user = mysql_fetch_object($res);

  // make sure the user exists
  if ($user) {
    // verify the submitted credentials
    if (crypt($password, $user->password) == $user->password) {
    } else {
      $error_msg = "Incorrect password.  Please try again:";
      $error_redirect = "login.phtml";
    }
  } else {
    // username does not exist in the database
    $error_msg =
      "$username is unregistered. <a href=\"submit_register.phtml?username=$username\">Register it now</a>, or try again:";
    $error_redirect = "login.phtml";
  }
} else {
  $error_msg = "Enter both username and password to log in:";
  $error_redirect = "login.phtml";
}

if ($error_msg) {
  session_register("error_msg");
  header("Location: $error_redirect");
  exit;
}

// save some info in the session so other pages can access it later
// in the session
$authenticated_username = $user->username;
session_register("authenticated_username");

$user_id = $user->user_id;
session_register("user_id");

// cache some other commonly used information
$query = <<<EOT
SELECT bozo
  FROM user_bozo
 WHERE user_id='$user_id'
EOT;

// array of usernames to be filtered on
$bozos = array();
$res = mysql_query($query)or
  die(error_page(mysql_error()));
while ($bozo = mysql_fetch_array($res)) {
  array_push($bozos, $bozo[0]);
}
natcasesort($bozos);
session_register("bozos");

// bozo array as a set suitable for use in a sql NOT IN string
$b = array();
foreach ($bozos as $x) {
  array_push($b, "'$x'");
}
$bozo_set = '(' . implode(", ", $b) . ')';
session_register("bozo_set");

// $back_to is the location where the user originally clicked the "log
// in" link
session_unregister("back_to");
header("Location: ". $back_to);
//echo $back_to;
?>

