<HTML>
<HEAD>
<TITLE>Swinney.org Pink re-Submit Form</TITLE>
</HEAD>

<BODY BGCOLOR="pink" TEXT="black">	

<form action="http://swinney.org/journals/process_article.phtml" method=post>
<TABLE WIDTH=400 BORDER=0 CELLSPACING=0 CELLPADDING=0>



<TR>
<TD>Name</TD>
<TD ALIGN="right">

<INPUT TYPE=TEXT NAME=username VALUE="<? echo $username; ?>" SIZE=30 maxlength=50>

</TD>
</TR>

<TR>
<TD>Website or email</TD>
<TD ALIGN="right">
<INPUT TYPE=TEXT NAME=web SIZE=30 maxlength=50>
</TD>
</TR>

<TR>
<TD>
<P>Title</P>
</TD>
<TD ALIGN="right">
<INPUT TYPE=text NAME=title SIZE=30 maxlength=50>
</TD>
</TR>

<TR>
<TD>
<P>Blurb</P>
</TD>
<TD ALIGN="right">
<INPUT TYPE=text NAME=blurb SIZE=30 maxlength=255>
</TD>
</TR>


<TR>
<TD ALIGN="left">
<P>Keywords (delimited by commas)</P>
</TD>
<TD ALIGN="right">
<INPUT TYPE=text NAME=keywords SIZE=30 maxlength=100>
</TD>
</TR>


<TR>
<TD COLSPAN=2>
 <P>Please enclose your paragraphs in <TT>&lt;P&gt;...&lt;/P&gt;</TT> tags.  If you don't know what that means, then don't worry about it.</P>

<TEXTAREA TYPE=text  NAME=content COLS=50 ROWS=20 wrap=virtual></TEXTAREA>
</TD>
</TR>
</TABLE>


<P>What category best describes you?</P>

<?
  include "admin/connect.inc";
  $res = mysql("", "SELECT * FROM categories ORDER BY name ASC");

  while ( $d = mysql_fetch_object($res) ) {
    echo "<input type='checkbox' name='cat$d->category_id'> $d->name <br>";
  }

?>

<INPUT TYPE="SUBMIT">   <INPUT TYPE="RESET">

</form>
</BODY>
</HTML>

































