<?
#$Id$
// insert banner
include "global.inc";
 include "templates/top.inc";
 echo "<CENTER>";
 include "banners/ghetto.inc";

$res = mysql_query ("SELECT DISTINCT username, count(username) AS number FROM articles_info GROUP BY username");

  echo "<TABLE><TR>";

  // initialize index at zero for modulo
  $index = 0;



while ($d = mysql_fetch_object($res)) {
  echo "<TD><a href='userpages.phtml?username=$d->username'>$d->username($d->number)</a></TD>\n";

  // increment the index for modulo
  $index++;
  $remainder = $index % 5;

  if ($remainder==0) {
  echo "</TR><TR>\n";  
  }

}


echo "</TR></TABLE>";

include "templates/footer.inc";
?>








