<?
// $Id$

require_once("./global.inc");
require_once("./templates/top.inc");

// have an incrementing number in the filename

if (! isset($index)) {
  $index = 0;
}

if ($index <= 0) {
  echo <<<EOT
<P>
If you have any images to upload for this article, select them here,
otherwise click <a href="index.phtml">continue</a>.
</P>

EOT;
} else if ($index < 5) {
  echo <<<EOT
<P>
You have uploaded <b>$index</b> images for this article<br>
If you have any <b>more</b> images to upload for this article,
select them here.
</P>
<P>
Otherwise click <B>exit</B>.
</P>

EOT;

  $query = <<<EOT
UPDATE articles_info
   SET image='$index'
 WHERE article_id='$article_id'
EOT;

  if (! mysql_query($query)) {
    $error_msg = "Problem saving image: " . mysql_error();
    echo <<<EOT
<p>
<b><font color="red">$error_msg</font></b>
</p>

EOT;
  }
}

if ($index < 5) {
  echo <<<EOT
<br>

<form action="process_image.phtml" method="POST" type="multipart/form-data">
<P>file: <input type="file" name="userfile"></P>
<input type="hidden" name="article_id" value="$article_id">
<input type="hidden" name="index" value="$index"><br>
<input type="submit" name="submit_image" value="submit">
<input type="submit" name="exit" value="exit">
</form>
</FONT>

EOT;
} else {
  echo <<<EOT
<p>
You may not upload any more images for this article.<br>
<a href="./index.phtml">Continue</a>
</p>

EOT;
}

include("./templates/footer.inc");
?>
