<?
// $Id$
require_once("global.inc");

// doesn't make sense to display the register page for users who are
// already logged in
if ($authenticated_username) {
  header("Location: " . $HTTP_REFERER);
}

// submit_register.phtml
$inc = "index";
$title = "Register a New Account";
$into_template = "submit_register.inc";
include "template_norollcall.inc";
?>

















































