<?
// $Id$ 
?>

<tr>
<td>
<table cellpadding="0" cellspacing="0" border="0">
<tr>
<td>
<img src="journals/img/name.gif" alt="name:" width="40" height="17" border="0"></td>

<td>
&nbsp;</td>

<td>
<img src="journals/img/thought.gif" alt="thought:" width="53" height="17" border="0"></td>

<td>
<form name="ithoughtitform" action="journals/process_thought.phtml" method="POST" enctype="multipart/form-data" >
&nbsp;</td>
</tr>

<tr>
<td>
<input type="text" size="10" name="username" value="<? if ($authenticated_username) { echo "$authenticated_username"; } ?>"></td>

<td>
&nbsp;</td>

<td>
<input type="text" name="thought"></td>

<td>&nbsp;<script type="text/javascript" language="JavaScript">
//<!--
document.write('<a href="javascript:document.ithoughtitform.submit()" target="_top" onmouseover="MM1.mouseOver(); window.status=\'I Thought It\'; return true" onmouseout="MM1.mouseOut(); window.status=\' \'; return true"><img src="journals/img/ithoughtit.gif" width="83" height="22" alt="I Thought It" name="ithoughtit" border="0"></a>');
//-->
</script>

<noscript>
<input type=submit value="I Thought It">
</noscript></td>
</form></tr>
</table></td>
</tr>
