i am working on this, be patient.  it works, just not well. --austin <BR><BR>

<form action="process_comment.phtml" method=post enctype="multipart/form-data">
<input type="hidden" name="article_id" value="<? echo "$article_id" ?>">

<TABLE BORDER=0 CELLSPACING=0 CELLPADDING=0>
<TR>
<TD>
<INPUT TYPE=TEXT NAME=username value='<? echo "$username" ?>' SIZE=15 maxlength=30 wrap=hard>
</TD>
</TR>

<TR>
<TD>
<TEXTAREA TYPE=text  NAME=comment COLS=60 ROWS=20 wrap=hard><? echo "$comment" ?></TEXTAREA>
</TD>
</TR>
<TR>
<TD>
<?php
echo(stripslashes($comment));
 ?>
</TD>
</TR>
</TABLE>



<!-- BEGIN SUBMIT ARTICLE CATEGORIES -->

<P>What category best describes you?</P>

<?
  include "admin/connect.inc";
  $res = mysql("", "SELECT * FROM nature ORDER BY nature_id ASC");

  while ( $d = mysql_fetch_object($res) ) {
    echo "<input type='radio' name='nature' value='$d->nature_id'> $d->nature <br>";
  }



?>
<INPUT TYPE="SUBMIT" VALUE="I said it">   <INPUT TYPE="RESET" VALUE="reset">

</form>






