<?
include "global.inc";
conn();  


##################################################
##################################################
## THIS IS THE BEGINING OF STAGE TWO, PROCESSING
## THE ARTICLE.  ROCK ON OALKAND.  ROCK ON SANTA
## CRUZ.  PRETZELS, THEY ARE GOOD.


if ($page=="submit") 

{



// include the top with the global include 

echo "<form action=\"submit_article.phtml?page=process\" method=post>\n";
echo "<TABLE WIDTH=400 BORDER=0 CELLSPACING=0 CELLPADDING=0>\n";
echo "<TR><TD COLSPAN=2>page: $page</TD></TR>\n";
echo "<TR>\n";
echo "<TD>Name</TD>\n";
echo "<TD ALIGN=\"right\">\n";



if (isset($username)) 

{
	echo "\n<TT>ck</TT><INPUT TYPE=TEXT NAME=username VALUE=$username SIZE=30 maxlength=50>";

}

	else

{

	echo "\n<INPUT TYPE=TEXT NAME=username SIZE=30 maxlength=50>";

}

echo "\n</TD>";
echo "\n</TR>";

echo "\n<TR>";
echo "\n<TD>Website or email</TD>";
echo "\n<TD ALIGN=\"right\">\n";

if (isset($web))

{

	echo "\n<TT>ck</TT><INPUT TYPE=TEXT NAME=web VALUE=$web SIZE=30 maxlength=50>\n";

}

	else

{
	echo "\n<INPUT TYPE=TEXT NAME=web SIZE=30 maxlength=50>\n";

}

echo "\n</TD>";
echo "\n</TR>";

echo "\n<TR>";
echo "\n<TD>";
echo "\n<P>Title</P>";
echo "\n</TD>";
echo "\n<TD ALIGN=\"right\">";

if (isset($title))

{

	echo "\n<TT>ck</TT><INPUT TYPE=text NAME=title VALUE=$title SIZE=30 maxlength=50>";

}

	else

{

        echo "\n<INPUT TYPE=text NAME=title SIZE=30 maxlength=50>";

}

echo "\n</TD>";
echo "\n</TR>";

echo "\n<TR>";
echo "\n<TD>";
echo "\n<P>Blurb</P>";
echo "\n</TD>";
echo "\n<TD ALIGN=\"right\">";

if (isset($blurb))

{       
        
	echo "\n<TT>ck</TT><INPUT TYPE=text NAME=blurb VALUE=$blurb SIZE=30 maxlength=255>";


}       
        
        else

{       
        
	echo "\n<INPUT TYPE=text NAME=blurb SIZE=30 maxlength=255>";


}



echo "\n</TD>";
echo "\n</TR>";


echo "\n<TR>";
echo "\n<TD ALIGN=\"left\">";
echo "\n<P>Keywords (delimited by commas)</P>";
echo "\n</TD>";
echo "\n<TD ALIGN=\"right\">";


if (isset($keywords))

{       

echo "\n<TT>ck</TT><INPUT TYPE=text NAME=keywords VALUE=$keywords SIZE=30 maxlength=100>";

}       
        
        else

{     
  
echo "\n<INPUT TYPE=text NAME=keywords SIZE=30 maxlength=100>";        

}



echo "\n</TD>";
echo "\n</TR>";


echo "\n<TR><TD COLSPAN=2>";
echo "\n<P>Please enclose your paragraphs in <TT>&lt;P&gt;...&lt;/P&gt;</TT> tags.";
echo "\n  If you don't know what that means, then don't worry about it.</P>";

if (isset($text)) {

echo "\n<TEXTAREA TYPE=text  NAME=text COLS=50 ROWS=20 wrap=virtual>$text</TEXTAREA>";

} 

else 

{

echo "\n<TEXTAREA TYPE=text  NAME=text COLS=50 ROWS=20 wrap=virtual></TEXTAREA>";
 
}

echo "\n</TD>".
     "\n</TR>".
     "\n</TABLE>";


echo "\n<P>What category best describes you?</P>";

  
$res = mysql_query ( "SELECT * FROM categories ORDER BY name ASC");


echo "\n<TABLE><TR>";
$index=1;
while ( $d = mysql_fetch_object($res) ) 

{

	$index++;
	$remainder = $index % 3;

	echo "\n<TD><input type='checkbox' name='cat$d->category_id'> $d->name </TD>";

	if($remainder==0)

	{

		echo "\n</TR><TR>";

	}


}

echo "\n</TR></TABLE>";


echo "<input name='page' type='submit' value='process'>\n";
echo "<input name='page' type='submit' value='preview'>\n";

echo "\n</form>\n";

}


##################################################
##################################################
## THIS IS THE BEGINING OF STAGE ONE, PROCESSING
## THE ARTICLE.  ROCK ON OALKAND.  ROCK ON SANTA
## CRUZ.  PRETZELS, THEY ARE GOOD.


if ($page=="process")

{



  // Init the date and time
  $date = date("Y-m-d");
  $time = time();

  if ( empty($username)) {
    echo "This username is not set";
    exit;
  }
/*
  // Work out what subjects
  $res = mysql_query ("SELECT MAX(category_id) FROM categories");
  $maxid = mysql_result($res, 0, 0);
  $subject_value = 0;
  for ( $i = 1 ; $i <= $maxid ; $i++ ) {
    $str = "cat".$i;
    if ( $$str == "on" ) {
      $val = pow(2, $i-1);
      $subject_value += $val;
    }
  }
*/
// get the users ip address.  maybe this is uncool, but i think it is a
// necessary precaution.  like dont i want to know who the person is who
// tries to send malicious unix commands in to the thoughts database?

$ip_addr = getenv ("REMOTE_ADDR"); // get the ip number of the user

  // Insert into the database
  $res = mysql_query("INSERT INTO articles_info
	 VALUES ( 
	'NULL', 
	'$username', 
        '$web',
	'$date', 
	'$time', 
	'1', 
	'".addslashes($keywords)."',
	'".addslashes($title)."',
	'".addslashes($blurb)."', 
	'$category',
	'$image',
	'$ip_addr'
	)");

  if ( $res == false ) { 
    echo("Bullocks on one!");
    exit;
  }



# Create a file in  /articles_info
# if you don't have the auto_increment integer, 
# then mysql_insert_id is not going to work
  $article_id = mysql_insert_id();
  $text = addslashes($text);

  $res = mysql_query("INSERT INTO articles_text VALUES ($article_id,'$text')");

  if ( $res == false ) { 
    echo("Bullocks on two!");
    exit;
  }

 strip_tags($blurb);
 strip_tags($text);
 mail("articles@swinney.org","$username wrote $title", "$blurb\n $text");

# get ready to loop

# exits
header("Location: submit_article.phtml?page=check");

} 


if ($page=="preview") {

echo "<H1>title: 	$title</H1>\n";
echo "<H2>blurb: 	$blurb</H2>\n";
echo "<H3>author: 	$author</H3";
echo "<H4>web: 		$web</H4>";
echo "<H5>body:</H5><P>$text</P>";

}
?>









