<?php
// -*- Mode: PHP; indent-tabs-mode: nil; =*-
///////////////////////////////////////////////
// $Id$
// for setting and changing statuses
require_once("../global.php");
include_once("./top.inc");
include_once("./nav.inc");

//
// if the article id is set then it is time to 
// work with the status of that aritcle.
//
if (isset($id)) {
  $query="SELECT title, status FROM articles_info WHERE article_id=$id";
  $res=mysql_query($query) or die (error_page($query));
  $row=mysql_fetch_row($res);
  $title=$row[0];
  $status=$row[1];
  ?>
<TABLE BORDER=1 CELLSPACING=0 CELLPADDING=5>
<TR>
<TD>title:</TD><TD><? echo $title; ?></TD>
</TR>
<TR>
<TD>id:</TD><TD><? echo $id; ?></TD>
</TR>
<TR>
<TD VALIGN="TOP">status:</TD><TD>
<FORM METHOD="POST" ACTION="process_status.php?id=<? echo $id;?>">
<INPUT TYPE="radio" NAME="status" VALUE=1<? if ($status==1) echo " checked";?>>pending<BR>
<INPUT TYPE="radio" NAME="status" VALUE=2<? if ($status==2) echo " checked";?>>active<BR>
<INPUT TYPE="radio" NAME="status" VALUE=3<? if ($status==3) echo " checked";?>>archive<BR>
<INPUT TYPE="radio" NAME="status" VALUE=4<? if ($status==4) echo " checked";?>>trash<BR>
<INPUT TYPE="SUBMIT" NAME="submit" VALUE="update">
</FORM>
</TD>
</TR>
</TABLE>
  <?
}

include_once("./bottom.inc");
?>

