<?
##############################################
# $Id$
require_once("../global.inc");
#
# set aindex
session_register("aindex");

include("./top.inc");
include("./nav.inc");


$query="SELECT image FROM articles_info WHERE article_id=$id";
$res=mysql_query($query) or die (error_page("$query"));
$aindex=mysql_result($res,0,0);




if ($error_msg) {
  echo <<<EOT
<p>
<b><font color="red">$error_msg</font></b>
</p>

EOT;
  session_unregister("error_msg");
}

// have an incrementing number in the filename
if (! isset($index)) {
  $index = 0;
}

if (isset($id)) {
  $query="SELECT title FROM articles_info WHERE article_id=$id";
  $res=mysql_query($query);
  $title=mysql_result($res,0,0);
}

if ($aindex <= 0) {
  echo <<<EOT
<P>
If you have any images to upload for <B>$title</B>, select them here,
otherwise click exit.
</P>

EOT;
} else if ($aindex < 1000) {
  echo <<<EOT
<P>
You have uploaded <b>$aindex</b> images for <B>$title</B><br>
If you have any <b>more</b> images to upload for this article,
select them here.
</P>
<P>
Otherwise click <B>exit</B>.
</P>

EOT;
}

if ($index < 5) {
  echo <<<EOT
<br>

<form action="process_image.phtml?id=$id" method="POST" enctype="multipart/form-data">
<P>file: <input type="file" name="userfile"></P>
<input type="submit" name="submit_image" value="submit">
<input type="submit" name="submit_image" value="exit">
</form>
</FONT>

EOT;
} else {
  echo <<<EOT
<p>
You may not upload any more images for this article.<br>
<a href="./article_info.phtml?id=$id">Continue</a>
</p>

EOT;
}

include("./bottom.inc");
?>
