
<a href="art/galleries/shitstick/index.htm"><img src="art/galleries/shitstick/thumbnails/copcar.jpg"  height=100 alt="another round at the ole shitstick"></a>

<a href="art/galleries/ole_rustic/index.htm"><img src="art/galleries/ole_rustic/thumbnails/Untitled-1.jpg"  height=100 alt="at the ole rustic"></a> 

<a href="art/galleries/elly/peach/index.phtml"><img src="art/galleries/elly/peach/ellypeach.jpg" height=100 alt="elly's peach"></a> 

<a href="art/galleries/desert/index.htm"><img src="art/galleries/desert/thumbnails/2000_08_08_desert_sky_original.jpg" height=100 alt="drive from austin to los angeles"></a> 

<a href="art/galleries/nyc/index.htm"><img src="art/galleries/nyc/thumbnails/2873_009.jpg" text-align=bottom alt="trip to new york city"></a>