<?
#$Id$
include "journals/global.inc";
include "journals/templates/top.inc";
?>
<CENTER>
<TABLE CELLSPACING=0 CELLPADDING=5><TR><TD COLSPAN=2 ALIGN="CENTER">

<TABLE width="100%" cellpadding="4"><TR><TD valign="top">
<p>
<b>(
<?
if ($authenticated_username) {
} else {
  echo '<a href="journals/login.phtml" accesskey="l">LOG IN</a> | ';
}
?>
<a href="journals/index.phtml" accesskey="j">JOURNAL</a> | 
<a href="journals/comments.phtml" accesskey="c">COMMENTS</a> | 
<a href="journals/submit_article.phtml" accesskey="s">SUBMIT</a> | 
<a href="journals/faq.phtml" accesskey="f">ANSWERS</A>
<?
if ($authenticated_username) {
  echo ' | ';
  echo '<a href="journals/vip/index.phtml" accesskey="v">VIP</a> | ';
  echo '<a href="journals/process_logout.phtml" accesskey="l">LOG OUT</a> ';
}
?>
)</b>
</p>
</td>
</tr>
<tr>
<td>
<? 
// include the thoughts
include "journals/submit_thought.phtml";
include "journals/insert_thought.phtml"; 
?>
</TD>
</TR></TABLE></center>
</TD></TR><TR><TD VALIGN="top">
<CENTER><TT>order</TT></CENTER>
<?
 include "journals/insert_titles.inc";
?>
</TD>
</tr><tr>
<TD valign="top">
<CENTER><TT>chaos</TT></CENTER>
<?
 include "journals/insert_5rand.inc";
?>

</TD></TR><TR><TD COLSPAN=2>

<? include "journals/insert_stats.inc"; ?>
  
</TD></TR></TABLE>
</CENTER>
<?
include "journals/templates/footer.inc";
?>
