
<?
include "journals/templates/top.inc";
// include global
include "journals/global.inc";
?>
<CENTER>
<TABLE CELLSPACING=0 CELLPADDING=5><TR><TD COLSPAN=2 ALIGN="CENTER">
<?
// insert banner
// include "journals/banners/rand_banner.inc";
?>
<!-- </TD></TR><TR><TD COLSPAN=2 ALIGN="center"> -->
<TABLE width="100%" cellpadding="4"><TR><TD valign="top"><b>
<p>(
<a href="journals/index.phtml" accesskey="j">JOURNAL</a> |
<a href="journals/comments.phtml" accesskey="c">COMMENTS</a> |   
<a href="journals/submit_article.phtml" accesskey="s">SUBMIT</a> | 
<a href="journals/faq.phtml" accesskey="f">ANSWERS</A>)</p></b>
</b>
</td>
</tr>
<tr>
<td>
<? 
// include the thoughts
include "journals/submit_thought.phtml";
include "journals/insert_thought.phtml"; 
?>
</TD>
</TR></TABLE></center>
</TD></TR><TR><TD VALIGN="top">
<CENTER><TT>order</TT></CENTER>
<?
 include "journals/insert_5articles.inc";
?>
</TD>
</tr><tr>
<TD valign="top">
<CENTER><TT>chaos</TT></CENTER>
<?
 include "journals/insert_5rand.inc";
?>

</TD></TR><TR><TD COLSPAN=2>

<? include "journals/insert_stats.inc"; ?>
  
</TD></TR></TABLE>
</CENTER>
<?
include "journals/templates/footer.inc";
?>







