

<?
include "journals/templates/top.inc";
// include global
include "journals/global.inc";
?>
<CENTER>
<TABLE CELLSPACING=0 CELLPADDING=5><TR><TD COLSPAN=2 ALIGN="CENTER">
<?
// insert banner
// include "journals/banners/rand_banner.inc";
?>
<!-- </TD></TR><TR><TD COLSPAN=2 ALIGN="center"> -->
<TABLE><TR><TD>
<p align="center">(<a href="journals/index.phtml">JOURNAL</a> |
<a href="journals/comments.phtml">COMMENTS</a> |   
<a href="journals/submit_article.phtml">SUBMIT</a> | 
<a href="journals/faq.phtml">ANSWERS</A>)</p>

<? 
// include the thoughts
include "journals/submit_thought.phtml";
include "journals/insert_thought.phtml"; 
?>
</TD></TR></TABLE>
</TD></TR><TR><TD VALIGN="top">
<CENTER><TT>5 new</TT></CENTER>
<?
 include "journals/insert_5articles.inc";
?>
</TD><TD valign="top">
<CENTER><TT>5 old</TT></CENTER>
<?
 include "journals/insert_5rand.inc";
?>

</TD></TR><TR><TD COLSPAN=2 ALIGN="CENTER">

<? include "journals/insert_stats.inc"; ?>

</TD></TR></TABLE>
</CENTER>
<?
include "journals/templates/footer.inc";
?>



